### ISSUE TITLE
pokesniper v1.5.2  force close...

### ISSUE THREAD

**Issue by 1wq21010** [pokesniperandroid/PokeSniper-Android#100]
Hello.
My device is lolipop 5.0.2 version and galaxy alpha
A problem is force close automatically when i try to start the app.
i already cleared cache, unistalled app and installed again
Keep up with the good work.

**Comment by mokenneth** [comment]
me too

samsung galaxy note 3 os5.0

**Comment by neoterrybogard** [comment]
Me to samung note 3 android 5.0

**Comment by pokesniperandroid** [comment]
it's known bug in samsung devices running on android 5.x lollipop

#96
