### ISSUE TITLE
Pokemon drop down list

### ISSUE THREAD

**Issue by adyjob2012** [pokesniperandroid/PokeSniper-Android#101]
The pokemon drop down list is improper. They are not sorted well.
Suggest to sort it by Ascending or if possible can manually type and show the possible result.

**Comment by TigerTheDark** [comment]
Manually type would be awesome

**Comment by pokesniperandroid** [comment]
Hi,

Please update to latest release v1.5.3
Its been updated to be editable with autocomplete

Thanks
