### ISSUE TITLE
Version wrong

### ISSUE THREAD

**Issue by TigerTheDark** [pokesniperandroid/PokeSniper-Android#102]
Hi devs , first of all great job, pokesniper works great! 
I've noticed that below "Snipe Those Bitches" its says VERSION 1.5.0 ... For some dummies outthere this is a huge problem.. not for me psshh, haha , thats all, great job again and thank you.

**Comment by pokesniperandroid** [comment]
Fixed in latest release v1.5.3 and thanks for the report.
