### ISSUE TITLE
App crashing 1.5.3 motoG4+

### ISSUE THREAD

**Issue by TigerTheDark** [pokesniperandroid/PokeSniper-Android#104]
Tried to reinstall app and reboot device but issue persist, the app was working hours ago though so I was wondering if there is something on your side, thanks in advance.

**Comment by kingkai808** [comment]
Same here app force crashes after clicking snipe

**Comment by sapukasibersih** [comment]
I also cant snipe..force close..app crash after clickibg snipe..

**Comment by pokesniperandroid** [comment]
Update to latest version, this issue should been fixed

**Comment by kingkai808** [comment]
Remote server error now

**Comment by pokesniperandroid** [comment]
Hi, seems fine to us. Try to check your internet connection.

http://imgur.com/a/Sbp12

**Comment by sapukasibersih** [comment]
Tq pokesniperandroid..

**Comment by pokesniperandroid** [comment]
#124
