### ISSUE TITLE
Force Closed. Please help!

### ISSUE THREAD

**Issue by samchoi02** [pokesniperandroid/PokeSniper-Android#105]
I am using Samsung's Note3 At the moment, I've tried 1.5.0 ~ 1.5.3 and every single application Force crashes. Please fix this problem ASAP. But other than that. Great app, I appreciate your work!

**Comment by pokesniperandroid** [comment]
Hi, currently PokeSniper will crash on any Samsung devices running android lollipop. Please refer to #96
