### ISSUE TITLE
remote server ERROR

### ISSUE THREAD

**Issue by icarlituxd** [pokesniperandroid/PokeSniper-Android#106]
http://image.prntscr.com/image/3605d220d094402a822019b601b381d5.png

samsung galaxy J7

**Comment by MrCrunchy** [comment]
Also getting server error when trying to open pokebag. Probably related issues.  S7 Edge

**Comment by GCHarald** [comment]
I get these errors, too. "Remote Server Error" when I try sniping or when I open the PokeBag.
Oneplus 2 - Android 6.0.1

**Comment by TigerTheDark** [comment]
I'm having the same issue ,

**Comment by unknowkir** [comment]
i have the same prob as well

**Comment by pokesniperandroid** [comment]
Try to update to latest version

**Comment by pokesniperandroid** [comment]
#124
