### ISSUE TITLE
sight

### ISSUE THREAD

**Issue by unknowkir** [pokesniperandroid/PokeSniper-Android#109]
i getting no pokemon sights: 0 for all pokemons

**Comment by TigerTheDark** [comment]
Sometimes I'm getting 0 but if a try again sniper gets it, other times give the remote server error and sometimes it's just closes...

**Comment by sapukasibersih** [comment]
Same with me..no pokemon sight:0

**Comment by pokesniperandroid** [comment]
Try to update to latest version
