### ISSUE TITLE
Remote server error 

### ISSUE THREAD

**Issue by RealLeonidas** [pokesniperandroid/PokeSniper-Android#110]
Was working fine before update.  Now,  literally every time I try to snipe I get remote server error.

**Comment by MrCrunchy** [comment]
Yup this is mentioned in previous posts.  We're all waiting for an update.  Gen 2 is slowly rolling out so... ^_^

**Comment by RealLeonidas** [comment]
Ahh,  okay.  Just irritating.  Want to get some gen 2 lol.

**Comment by pokesniperandroid** [comment]
Try to update to latest version

**Comment by TigerTheDark** [comment]
Ooooo yeaahh can do , thanks guys downloading right now

**Comment by RealLeonidas** [comment]
Just did,  still server error

**Comment by SamuelPGM** [comment]
THE REMOTE SERVER ERROR IS STILL ON (PLEASE FIX IT )     :(

**Comment by pokesniperandroid** [comment]
We just did a test and seems fine, no remote server error on v1.5.5. Try changing your network and report.

http://imgur.com/a/XKe4A

**Comment by RealLeonidas** [comment]
Tested again.  Same error.

**Comment by pokesniperandroid** [comment]
If anyone know VPN, try to use VPN and please report.

**Comment by pokesniperandroid** [comment]
#124
