### ISSUE TITLE
remote server error

### ISSUE THREAD

**Issue by nyzbabiboi** [pokesniperandroid/PokeSniper-Android#111]
I am still having the remote server error with the new update. V.1.5

**Comment by RealLeonidas** [comment]
SMe

**Comment by RealLeonidas** [comment]
Same*

**Comment by SamuelPGM** [comment]
Me too :(   ;(

**Comment by pokesniperandroid** [comment]
We just did a test and seems fine, no remote server error on v1.5.5. Try changing your network and report.

http://imgur.com/a/XKe4A

**Comment by RealLeonidas** [comment]
Several people are reporting it as not working though

**Comment by RealLeonidas** [comment]
Tested again.  Remote server error.

**Comment by pokesniperandroid** [comment]
If anyone know VPN, try to use VPN and please report.

**Comment by nyzbabiboi** [comment]
I tried it with the vpn, its still not working

**Comment by pokesniperandroid** [comment]
Try to update to v1.5.6-EXPERIMENTAL and please report. It works on us.

**Comment by pokesniperandroid** [comment]
#124
