### ISSUE TITLE
REMOTE SERVER ERROR 

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#112]
This error IS NOT FIXED, I have The latest Released version on Samsung Galaxy s7. BUT STILL, I CAN'T SNIPE THOSE BITCHES, AND GEN 2 IS ALREADY OUT, PLEASE FIX AS FAST AS POSSIBLE.... I haaaate Remote Server Error.

**Comment by SamuelPGM** [comment]
Fix the Remote server error as fast as possible please.

**Comment by pokesniperandroid** [comment]
We just did a test and seems fine, no remote server error on v1.5.5. Try changing your network and report.

http://imgur.com/a/XKe4A

**Comment by SamuelPGM** [comment]
No, I'm very sorry to say you're wrong  (trying to be polite), I've changed to 4g, Remote Error server, tried on normal WiFi, Remote error Server. Plus, the picture you linked, is from version 1.5.4, not the latest one, should I go to 1.5.4? Instead of 1.5.5? I'm A Samsumg S7 User (idk if there is anything to do with cellphone).

**Comment by SamuelPGM** [comment]
I've tried to Snipe, on both PTC and Google accounts, both ending up showing the unfortunate Remote Server Error, I've also downloaded version 1.5.5 again to try again, but still the error was there.... I'm so sad

**Comment by SamuelPGM** [comment]
But it is OK If you guys need time to fix a hard Bug, glitch, whatever. Niantic makes us wait more for things than anything in this world lol.

**Comment by chimsedinang123** [comment]
Hello.

 I downloaded version 1.5.5 on. Successfully installed, when you open up the remains pokesniper version 1.5.4. 3 times I had to reload the same thing happened. Thank addmin

**Comment by chimsedinang123** [comment]
Samsung E7  network 3G

**Comment by chimsedinang123** [comment]
I use google accuonts

**Comment by SamuelPGM** [comment]
I need to download 1.5.5 3 times ?

**Comment by pokesniperandroid** [comment]
v1.5.5 still showing v1.5.4 inside the app, this was skipped

**Comment by chimsedinang123** [comment]
Ok. I had to erase and reload version 1.5.5 3 times but when the
installation is complete, it is still 1.5.4. I use google accounts

Vào 17-02-2017 12:41 PM, "pokesniperandroid" <notifications@github.com> đã
viết:

**Comment by SamuelPGM** [comment]
Ok I got it, but For some reason REMOTE SERVER ERROR is still there... do you pokesniper have any idea of what may be causing this issue?

**Comment by chimsedinang123** [comment]
Ok. Thank you.

**Comment by YirenTan** [comment]
So is there a fix yet? It shows v1.5.4 in the app

**Comment by chimsedinang123** [comment]
Addmin answered already. Do you understand what the problem is not ?. 1 is
due to your PVN matter
2. Do niantic server .. you should find people with knowledge of the PVN
for reference. Thank

Vào 17-02-2017 12:47 PM, "SamuelPGM" <notifications@github.com> đã viết:

**Comment by chimsedinang123** [comment]
Error app

Vào 17-02-2017 12:52 PM, "YirenTan" <notifications@github.com> đã viết:

**Comment by chimsedinang123** [comment]
Addmin for help. App log on and until all fruit is prepared manually close the app. Thank

**Comment by pokesniperandroid** [comment]
Try to update to v1.5.6-EXPERIMENTAL and please report. It works on us.

**Comment by pokesniperandroid** [comment]
#124
