### ISSUE TITLE
Crashing Just after "Use Razz Berry"

### ISSUE THREAD

**Issue by YirenTan** [pokesniperandroid/PokeSniper-Android#113]
Am using Samsung Galaxy S7 and I have encountered Remote server error once and it keeps crashing

**Comment by SamuelPGM** [comment]
Mine is just Remote Server error, no razz Berry involved. (Galaxy S7)

**Comment by YirenTan** [comment]
Mine is opposite of yours now. No remote server error, just crashing

**Comment by rank001** [comment]
me, too
stop app (S7 - 7.0)

**Comment by chimsedinang123** [comment]
Addmin for help. App log on and until all fruit is prepared manually close the app. Thank

**Comment by YirenTan** [comment]
@pokesniperandroid
 
It is still crashing when attempting to catch pokemon

**Comment by unknowkir** [comment]
Samsung galaxy note 4 android 6.0. I have the same problem here... :/

**Comment by pokesniperandroid** [comment]
#124
