### ISSUE TITLE
Gen 2

### ISSUE THREAD

**Issue by cire27rn** [pokesniperandroid/PokeSniper-Android#116]
Why there are gen 2 pokemons in the pokesniper?

**Comment by Hack-Ninja023** [comment]
They were released today (well yesterday the 17th)

**Comment by cire27rn** [comment]
I mean. There are no gen 2 pokemons in the pokesniper.

**Comment by MrCrunchy** [comment]
When a new update comes out usually takes a few days for an updated hack. Give it a few days.
