### ISSUE TITLE
New update is still 1.5.4

### ISSUE THREAD

**Issue by kingkai808** [pokesniperandroid/PokeSniper-Android#117]
Downloaded 1.5.5 update 4 times and it is still showing 1.5.4 version in pokesniper.
Deleted and reinstalled 4 times. Download link is bugged with old update

**Comment by kingkai808** [comment]
@pokesniperandroid

**Comment by pokesniperandroid** [comment]
Sorry, this was our mistake (skipped when release). The app version still 1.5.5 nonetheless.

**Comment by kingkai808** [comment]
Still getting remote server error with new update.

**Comment by kingkai808** [comment]
@pokesniperandroid

**Comment by pokesniperandroid** [comment]
Try to update to v1.5.6-EXPERIMENTAL and please report. It works on us.

**Comment by kingkai808** [comment]
Still have remote error. @pokesniperandroid
On new update

**Comment by kingkai808** [comment]
I can play pogo just fine.

**Comment by pokesniperandroid** [comment]
The weird thing is, it works fine on us without any modification. Try create new PTC account and use it, is it giving same result?

**Comment by chimsedinang123** [comment]
Hello. I can not download pokesniper 1.5.6. Why ? Thank

**Comment by SamuelPGM** [comment]
Experimental 1.5.6 is not working, SERVER REMOTE ERROR

**Comment by kingkai808** [comment]
I used 5 different PTC accounts. 2 different vpns. 2 different hard ips

**Comment by pokesniperandroid** [comment]
Try to update recent version and report.

**Comment by kingkai808** [comment]
Force closing now after hitting snipe. Deleted reinstalled new update and still force close.

**Comment by pokesniperandroid** [comment]
@kingkai808 did you use hash key? if yes, redownload the apk, we uploaded the wrong build.

**Comment by kingkai808** [comment]
Not using the hash key

**Comment by pokesniperandroid** [comment]
@kingkai808 

Okay, so the app crash sometimes (we just tried it). Probably because the recent API changes. 
Try to snipe again, we try to snipe again and didn't crash.

**Comment by kingkai808** [comment]
Crashes 10x out of 10. No successful snipes. Will keep trying. But so far crashed everytime

**Comment by pokesniperandroid** [comment]
@kingkai808 We tried 4 times,1 crashed.

**Comment by kingkai808** [comment]
Just tried 5 more times crashed each time.
Using galaxy s7 edge.

**Comment by pokesniperandroid** [comment]
See this screenshot, we just did a few minutes ago. 

http://i.imgur.com/wvXiFtK.png

![pokemon](http://i.imgur.com/wvXiFtK.png)

**Comment by kingkai808** [comment]
I see that but it's still not letting me not sure why

**Comment by pokesniperandroid** [comment]
@kingkai808 do you mind to test in on another device or emulator like Nox or genymotion?

**Comment by pokesniperandroid** [comment]
#124
