### ISSUE TITLE
Experimental version

### ISSUE THREAD

**Issue by cire27rn** [pokesniperandroid/PokeSniper-Android#118]
The experimental version works well on 3rd try. 1st is remote server error. 
2nd is that pokemon is not on sight. 
3rd is the success one 😉

**Comment by SamuelPGM** [comment]
YEAH BUT IT SHOULDN'T WORK LIKE THAT

**Comment by SamuelPGM** [comment]
On 4g, my Plan Goes away Like that, because of video Ads

**Comment by Hack-Ninja023** [comment]
Mine isn't working at all it days remote sever error :\

**Comment by MrCrunchy** [comment]
Mine isn't working at all.  Continuously remote server error.   Using the experimental version.

**Comment by EkoWijonarko** [comment]
In this version i got Force Closed while i try to second sniping. When the "Attempt to catch pokemon" than Force Closed.
I use Xiaomi Redmi Note WCDMA Kitkat OS.
I hope you can fix it next time.

**Comment by EkoWijonarko** [comment]
The experimental version works in 1st season sniping and 2nd season sniping not work.
1st is remote server error.
2nd is that pokemon is not on sight.
3rd attempt to catch pokemon than Force Closed.

**Comment by pokesniperandroid** [comment]
Try to update recent version and report.

**Comment by pokesniperandroid** [comment]
#124
