### ISSUE TITLE
Crash..

### ISSUE THREAD

**Issue by Nataniigor** [pokesniperandroid/PokeSniper-Android#119]
Im have a Android 6.0 (dooge x5 max) HELPP ! im have a 1.5.4 Pokesniper

**Comment by pokesniperandroid** [comment]
Try to update recent version and report.

**Comment by Nataniigor** [comment]
Crash....

**Comment by Nataniigor** [comment]
crash again , again , again

**Comment by pokesniperandroid** [comment]
Okay, this issue added to our known bugs. This caused the recent API changes. Try to snipe again and ignore this crashes for now until the API get fixed.

**Comment by Nataniigor** [comment]
Okeey! They could also quickly be arranged? Because the new generation came in and I would like to capturing Very! As soon as possible

**Comment by pokesniperandroid** [comment]
Yeah, but this app still can snipe 2nd gen. Screenshot capturing Natu (pokedex #177)

![pokemon](http://i.imgur.com/wvXiFtK.png)

**Comment by Nataniigor** [comment]
I understand but I throw the game when he caught EVERY Pokemon from the new and the old generation and throws just

**Comment by pokesniperandroid** [comment]
#124
