### ISSUE TITLE
remote server error on 1.5.6

### ISSUE THREAD

**Issue by nyzbabiboi** [pokesniperandroid/PokeSniper-Android#120]
I am still having the remote server error on the 1.5.6 experimental version

**Comment by RealLeonidas** [comment]
Same

**Comment by Yosnipe** [comment]
Same Problem here, using the experimental Version. Tryed Mobile Ethernet and WLAN, both doesnt Work.

**Comment by pokesniperandroid** [comment]
Try to update recent version and report.

**Comment by pokesniperandroid** [comment]
#124
