### ISSUE TITLE
WHERE IS YOUR RESPONSE TO REMOTE SERVER ERROR (MAIN BUG/ GLITCH)

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#121]
You 1.5.6 Experimental Doesn't actually change nothing, REMOTE SERVER ERROR is still in there, Gen2 Is already Here and we want to snipe, Please, If you're going to release a 1.5.6 (not experimental) or a 1.5.7, RELEASE IT WITHOUT ANY PROBLEMS, if there are problems in new versions it means your Apk Kinda of Sucks, or your crew, because if pokesniper don't work properly in any version, it only indicates your struggle to solve a "simple" REMOTE SERVER ERROR !!!! HURRY PLEASE, IT'S ALL I ASK YOU, but when released 1.5.7, MAKE SURE EVERYTHING IS FINE FOR FUCK SAKE.

**Comment by SamuelPGM** [comment]
I'm sorry for everyone having bad experiences with Such a useful app for pokemon go.

**Comment by pokesniperandroid** [comment]
Who are you again?

The version has been updated, try it.

And don't assume any bug is simple. Because majority users in our area didn't face this "REMOTE SERVER ERROR" issue.

**Comment by nyzbabiboi** [comment]
The new experimental version 2 is crashing the app

**Comment by SamuelPGM** [comment]
YOU FUCKER, ALL OF THESE NEW REPORTS ARE ABOUT REMOTE SERVER ERROR AND YOU SAY THAT ???? WTF

**Comment by pokesniperandroid** [comment]
We know this issue, dude. We don't try to hide it or something. And you just saying whatever you want. We try to fix it, but if the issue comes from like the server, API version. We don't have control over this.

**Comment by pokesniperandroid** [comment]
And try to see this screenshot, did this screnshot showing any REMOTE SERVER ERROR?

http://i.imgur.com/wvXiFtK.png

![pokemon](http://i.imgur.com/wvXiFtK.png)

**Comment by pokesniperandroid** [comment]
#124
