### ISSUE TITLE
app crashing on 1.5.6 experimental 2

### ISSUE THREAD

**Issue by nyzbabiboi** [pokesniperandroid/PokeSniper-Android#122]
With the new update the app crashes on trying to login

**Comment by pokesniperandroid** [comment]
@nyzbabiboi did you use hash key? if yes, redownload the apk, we uploaded the wrong build.

**Comment by nyzbabiboi** [comment]
I installed ut fresh and the app is just crashing. V1.5.6 experimental 2

**Comment by pokesniperandroid** [comment]
Okay, this issue added to our known bugs. This caused the recent API changes. Try to snipe again and ignore this crashes for now until the API get fixed.

**Comment by MrCrunchy** [comment]
How do we ignore the crashes if it crashes every time we try to snipe? :/

**Comment by MrCrunchy** [comment]
Not trying to be a jerk.  Just wondering if there's a work around I'm not aware of.

**Comment by pokesniperandroid** [comment]
@MrCrunchy If it's too annoying, just wait for API fix. The request to Niantic flagges as invalid on this recent API sometimes

**Comment by MrCrunchy** [comment]
So what you're saying is just keep trying to snipe and it will eventually not crash and capture?  That's where I'm confused.

**Comment by pokesniperandroid** [comment]
@MrCrunchy the app will still crashing, but if we lucky we can still snipe and didn't crash. Niantic probably using new detection against bots.

**Comment by pokesniperandroid** [comment]
#124

**Comment by MrCrunchy** [comment]
Got it.  Thanks.  😊
