### ISSUE TITLE
Crash v1.5.6-EXPERIMENTAL2

### ISSUE THREAD

**Issue by pokesniperandroid** [pokesniperandroid/PokeSniper-Android#124]
Rather creating issues for the same report, i'll organize and use this as main issue for v1.5.6-EXPERIMENTAL2

<b>Bugs</b>
- Crashes
- Remote Server Error

<b>Crashes Reason</b>
- Network request into Niantic server flagged as INVALID_PLATFORM_REQUEST so we got no response from Niantic and so parsing the response will be voided. Probably because the recent update 0.57.2 and released 2nd gen Pokemons.
- There's report on API's repo about INVALID_PLATFORM_REQUEST 

<b>Remote Server Error</b>
- Timeout to get response from server
- Incoming network request blocked (server-side)
- API detected

<b>Workaround (Temp)</b>
- Retry snipe until work (not crashing)
- Using previous release (if not encounter Remote Server Error)
- If it's too annoying, just wait for API fix

<b>Attachment</b>
- If you lucky and didn't get crashes, this will be the result (not facing any crash)
http://imgur.com/a/wWvPT [GIF]
- PR on API's repo with report on comment about INVALID_PLATFORM_REQUEST
https://github.com/Grover-c13/PokeGOAPI-Java/pull/865

**Comment by jayali619** [comment]
I tried 10 time constantly crashing

**Comment by pokesniperandroid** [comment]
@jayali619 see the workaround

**Comment by SamuelPGM** [comment]
Yeah Jaya.... Crashing a lot, the 1.5.5 and 1.5.6 Experimental 1, we're only Remote Server Error... but this new one is crash after crash, The funny thing : Each update takes out one glitch, but replaces another bad one lol

**Comment by pokesniperandroid** [comment]
@SamuelPGM yeah we know and we feel bad about this.

**Comment by SamuelPGM** [comment]
No problem, I know your Crew is trying Hard to make a Version that : Doesn't have bugs at all, no crash, no Remote Server Error, no Razz Berry error, ALL Gen 2 catchable, with all gen 1 Ok. All Functions working properly, maybe next one will make it all right. I have faith these bugs will fly away.    :)

**Comment by SamuelPGM** [comment]
Report : Crash also when trying to open Pokebag in PokeSniper, and when trying to Snipe a pokémon. Version 1.5.6 Experimental 2 .

**Comment by mokenneth** [comment]
force close on Samsung Galaxy note 3 running on Android 5.x Lollipop

**Comment by mochammadrizkyfj** [comment]
crash and force close and remote server error why?

**Comment by mochammadrizkyfj** [comment]
every catch force close every catch remote server error

**Comment by samchoi02** [comment]
Still crashing...

**Comment by sapukasibersih** [comment]
V1.5.6 experimental2 still force close..but i try 2 times and it succesfully worked..tq..tq..snipe2..hehe

**Comment by mokenneth** [comment]
i tried 3 times.  both v1.5.6 experimental 1 & 2~force close

**Comment by supergerman** [comment]
When is it ready? It crashes all the time.

**Comment by SamuelPGM** [comment]
Yeah,  I also want to know When the next update is coming.... and hopefully with everything working !

**Comment by chimsedinang123** [comment]
Hello . Do to app use fruits other than grapes. eg banana pineapple ... thank addmin

**Comment by chimsedinang123** [comment]
@pokesniperandroid

**Comment by pokesniperandroid** [comment]
So, we release new version but still experimental. We try to minimize the crash by handling possible exceptions.

**Comment by chimsedinang123** [comment]
Thank you very much. I'm using version 1.5.6 (2). So when the official release version of my then get automatically update?

**Comment by pokesniperandroid** [comment]
@chimsedinang123 if the current bug fixed, then we'll add fruits option and notify users. for now we're focusing on fixing bugs

**Comment by chimsedinang123** [comment]
When you log into the game, in version 0.57.2 will have a news announcement, it caught the player must click to continue. I suspect it might be a problem you are having. Thank

**Comment by mokenneth** [comment]
fyi

my Samsung Galaxy note 3 running on Android 5.x Lollipop still facing force close in Version 1.5.6 Experimental 1/2/3

**Comment by pokesniperandroid** [comment]
@mokenneth yeah, we received logs from some users and we found out that samsung running lollipop have conflict with database library. we'll try find alternative library for this issue.

**Comment by mokenneth** [comment]
really thanks a lot.  i also sent the log file to you

**Comment by pokesniperandroid** [comment]
Fixed on recent release.

**Comment by Emz2903** [comment]
I've used this app before and just installed the upgrade but getting the below error when pressing "snipe" 
![screenshot_20170221-225015](https://cloud.githubusercontent.com/assets/25940494/23189415/bb457c1c-f88a-11e6-99f7-80267cf3dff5.jpg)
