### ISSUE TITLE
V1.5.6 Experimental 3 : "Request To Server couldn't be started probably because INVALID_PLATAFORM_REQUEST, please try again."   

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#125]
That's what is showing up right now, it isn't crashing anymore, doesn't have REMOTE SERVER ERROR, but now it has this new bugh or whatever. Please, on the next Experimental, or on another version, don't dissappear a previous version bug, and bring up a new one, like happened to all Experimentals. 

Thank You!

**Comment by SamuelPGM** [comment]
*Bug

**Comment by SamuelPGM** [comment]
And I can't open Bag.

**Comment by pokesniperandroid** [comment]
Hello,

Yeah, as we stated before in the EXPERIMENTAL2, the current API giving this response. So, you could just try again until the error disappear (random) or wait for API fix. The PokeBag depend on the API too, so it gets the same response. 

<b>This error is random, sometimes appear and sometimes don't</b>

In the EXPERIMENTAL3, we handle the INVALID_PLATFORM_REQUEST to be printed as a log. The previous version didn't, so app crashes.

**Comment by andy1688878** [comment]
Only sussesful snipe one time ,and then appear INVALID_PLATAFORM_REQUEST

**Comment by chimsedinang123** [comment]
Thank you :D

**Comment by supergerman** [comment]
I tried it over 10 times. It says always INVALID_PLATFORM_REQUEST. Can you give us a new update without any bugs please? Appreciate your work!

**Comment by RealLeonidas** [comment]
Can you guys not read?  Lol jeez..

**Comment by cire27rn** [comment]
Its much better than crashing.

**Comment by supergerman** [comment]
But it does not snipe.

**Comment by nyzbabiboi** [comment]
Same

**Comment by andy1688878** [comment]
I successful snipe twice today ,it fxxkng lucky I am

**Comment by SamuelPGM** [comment]
Andy, I literally just tried to snipe 15 Times, none of them were successful, the Error is not random (I think) because 15 out of 15 times, that error appeared.  Pokesniper isn't working because of This new update Niantic release ("Gen2") And because of this API thing....

**Comment by SamuelPGM** [comment]
Pokesniper, just to clear up, Is there any thing you can do to help this API Error ?

**Comment by SamuelPGM** [comment]
Or whatever thing is making Pokesniper to not Work Properly.

**Comment by pokesniperandroid** [comment]
@SamuelPGM  Seems there's new commit for this issue on API's repo. Will update ASAP.

**Comment by kingkai808** [comment]
Api is bad don't use pokesniper until a new api and remastered one emerges. You WILL get banned for sending incorrect api requests to niatics servers. I.e current version = A and you're sending "B" version requests.

**Comment by supergerman** [comment]
When is the new update out without any bugs?

**Comment by pokesniperandroid** [comment]
@kingkai808 even if we're using A, Niantic still could see us using API because the unnatural catches (maybe)

Btw, version updated and should fix this issue.

**Comment by kingkai808** [comment]
They can but only catch obvious request atm. Until they hire 50 new data coders

**Comment by nyzbabiboi** [comment]
The account wont be banned right? I rather wait for better version then getting banned and wasting all my effort

**Comment by KHARUROSU** [comment]
Hi there, i have send you my log through experimental3. The bug with Samsung is still forcing close automatically right? 
Experimental4 still force close on those devices. 
Works fine on my tablet. 
Good work, hope you fix the bug :) 
Have a nice week.

**Comment by pokesniperandroid** [comment]
@KHARUROSU please refer to #127

#125 fixed on recent release.

**Comment by sandstorm267** [comment]
the error gas come back in experimental 6 it does not go away i have been trying. Pls help me.

**Comment by sandstorm267** [comment]
*has

**Comment by sandstorm267** [comment]
update been trying for the last 15 min error is not going away. Legend pls fix it.

**Comment by pokesniperandroid** [comment]
@sandstorm267 API is broken today, need to wait API fix.

**Comment by sandstorm267** [comment]
okay

**Comment by xiaoming93** [comment]
Hi I have been trying to snipe for nidorans but never once succeed may I know is there a solution??

**Comment by sandstorm267** [comment]
the API is broken give him time to fix it

**Comment by xiaoming93** [comment]
Thanks for the fix it's working again. But can anyone help me with sniping nidorans. Always show no nidorans found

**Comment by xiaoming93** [comment]
Thanks for the nidoran fix!!
