### ISSUE TITLE
v1.5.6-EXPERIMENTAL4 Crashing

### ISSUE THREAD

**Issue by samchoi02** [pokesniperandroid/PokeSniper-Android#126]
v1.5.6-EXPERIMENTAL4 Is crashing for me. I'm using Samsung Galaxy Note 3 Android 5.0 lollipop

**Comment by SamuelPGM** [comment]
OMG, FOR ME FINALLY WORKED !!!!

**Comment by SamuelPGM** [comment]
But please Pokesniper, I prefer to stay on Experimental 4, with everything alright to me rather than go to 1.5.6 and everything messed up, and even though it's working fine for me right now, it still isn't working for others, and that makes me sad.   :(

Keep Holding on People.
And keep working hard Pokesniper Crew !

Thanks.

**Comment by MrCrunchy** [comment]
I got soft ban when attempting even though I gps spoofed. anyone else getting soft ban?

**Comment by SamuelPGM** [comment]
If you use Fly Gps or other SpooFer... maybe you messed it up and imputed you home coordinates wrong, and that's the soft ban

**Comment by SamuelPGM** [comment]
For an example.... you spoofed yourself to new york

**Comment by SamuelPGM** [comment]
But then your home coordinate is on China

**Comment by MrCrunchy** [comment]
nah been using this since it first came out.. The reason you input your home coordinates into the app is to prevent the soft ban after you snipe something far far away. I'm wondering if it was just a fluke or if others are also experiencing? I got to go spin a pokestop 50 times...brb...

**Comment by MrCrunchy** [comment]
unbanned did it again, another soft ban. let me know if anyone else is experiencing this. My home coordinates are inputted correctly.

**Comment by SamuelPGM** [comment]
Damn, you're having an unpleasant problem unlucky fella lol

**Comment by MrCrunchy** [comment]
eh experimentals always have quirks to work out. I don't want to keep getting banned in case I get a perma ban. That would be very unlucky.

**Comment by pokesniperandroid** [comment]
Well, i'm not experiencing any softban so far. Try with different account, perhaps.

**Comment by MrCrunchy** [comment]
I'll make a new account see if that also experiences this and report back.  Maybe Niantic hates me catching them all :/

**Comment by MrCrunchy** [comment]
New account no problem...Niantic just hates me...maybe it's my player ID: IngressSucked

**Comment by andy1688878** [comment]
Well done 😀 start sniper those bitches

**Comment by pokesniperandroid** [comment]
I'll close this issue as its been fixed
