### ISSUE TITLE
Crash on Samsung devices running Android Lollipop 5.x

### ISSUE THREAD

**Issue by pokesniperandroid** [pokesniperandroid/PokeSniper-Android#127]
<b>Bugs</b>
- Crashes on Samsung devices running android lollipop 5.x

<b>Reason</b>
- Database library didn't created db properly and so the app can't read any data from database. There's been a report on libs repo.

<b>Workaround</b>
- For now, there's nothing. You need to wait for fix
- We need to change database libs 

This only affect said devices

**Comment by samchoi02** [comment]
Will we have to wait a long time?

**Comment by pokesniperandroid** [comment]
@samchoi02 try update to v1.5.6-EXPERIMENTAL5 and please report

**Comment by mokenneth** [comment]
the v1.5.6-EXPERIMENTAL5 still not worked with my Galaxy note 3 O.S 5

**Comment by lac2811** [comment]
Version "v1.5.6-EXPERIMENTAL5" still crashing on my Galaxy S4 with android 5.0.1

**Comment by pokesniperandroid** [comment]
Alright, please try EXPERIMENTAL6 and report the result.

**Comment by lac2811** [comment]
@pokesniperandroid "v1.5.6-EXPERIMENTAL6" It looks like everything's okay now! Working on my Samsung device.

Great work bro! Thx.

**Comment by pokesniperandroid** [comment]
@lac2811 well, that's great then.

how about you @samchoi02 @sandstorm267 and @mokenneth 
have you tried it?

**Comment by sandstorm267** [comment]
same i knew you would fix it well done

**Comment by mokenneth** [comment]
its ok now
 
thanks for your effort

**Comment by samchoi02** [comment]
@pokesniperandroid Wow! Thanks for the EXPERIMENTAL6 update! Finally works. you should close this issue now

**Comment by KHARUROSU** [comment]
@pokersniperandroid Works fine on my Samsung Alpha now. Thanks for fixing the bug. You are "The Man"  :)

**Comment by pokesniperandroid** [comment]
Fixed

**Comment by ramshakhar** [comment]
Always getting "Request to server couldn't started, please try again". 
Device: Samsung S7 Edge
App version: 1.5 EX 6

**Comment by KillerStrike17** [comment]
@ramshakhar same problem with me and my friend too, we are trying from past 12 hrs device Samsung s6 edge app version 1.5.6-experimental 6

**Comment by KillerStrike17** [comment]
@pokesniperandroid help

**Comment by pokesniperandroid** [comment]
@ramshakhar  @KillerStrike17 i've been posting the issue regarding API update. you should check issues page or navigate to #141
