### ISSUE TITLE
Error on Snipe Option

### ISSUE THREAD

**Issue by Emz2903** [pokesniperandroid/PokeSniper-Android#129]
I've used this app before and had no issues... I've just installed the update but get the attached error when pressing "snipe"

Any idea what I'm doing so wrong? :)
![screenshot_20170221-225015](https://cloud.githubusercontent.com/assets/25940494/23189598/9608eaa0-f88b-11e6-8c7f-18ce3cf3cd17.jpg)

**Comment by lac2811** [comment]
@Emz2903 I face the same error when i put the wrong password in google account. Try to put the right password again.

**Comment by Emz2903** [comment]
Hiya

Now I'm getting the attached error message?



-------- Original message --------

**Comment by Emz2903** [comment]
Hey.. now I'm getting the attached 
![screenshot_20170221-235700](https://cloud.githubusercontent.com/assets/25940494/23190739/a33ac6a2-f891-11e6-8391-875740d83c9d.jpg)

**Comment by lac2811** [comment]
@Emz2903 Try to snipe again

**Comment by chimsedinang123** [comment]
The other fruits were put into version 1.5.6 (6) not so addmin? Thank
