### ISSUE TITLE
Is there a paid version?

### ISSUE THREAD

**Issue by powerboxizm** [pokesniperandroid/PokeSniper-Android#13]
Ad free

**Comment by hanncreator** [comment]
I can help you ad free bro

**Comment by socbaysky** [comment]
@hanncreator please help me ad free. Thanks very much !

**Comment by hanncreator** [comment]
My apk ad free broo lol.
Please contact me via email cobuspotgie@gmail.com
I can give you pokesniper ad free

**Comment by kingkai808** [comment]
This
