### ISSUE TITLE
Cannot Catch Farfetch'd

### ISSUE THREAD

**Issue by MangoFighter** [pokesniperandroid/PokeSniper-Android#130]
No matter what coordinates for Farfetch'd i key into the latest version of pokesniper, it always says "No more Farfetch'd to catch" even though the pokemon is in sight and also after using razz berry.. Can you help to resolve this issue so that i can add Farfetch'd into my pokedex? It's the only Gen 1 pokemon i have yet to capture.. Hope to hear from your reply soon, thank you!

**Comment by chimsedinang123** [comment]
Me too

**Comment by pokesniperandroid** [comment]
Fixed in v1.5.7-BETA1
