### ISSUE TITLE
Pokezz 

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#131]
There is a lot of errors on Pokezz, when it comes to the app to say what is the IV from pokémon, and there are a lot of pokémon that are showing at the top of the highest pokémon iv, but when you catch that pokémon, it says that they have 36% Iv, instead of the 100% Iv that was being showed..... and a lot of pokémon that have 100+ Seconds to be catchable, and when you try to snipe him, it says: There is no more "Pokemon" to catch.
I don't know if you guys can do something but whatever.... is just to everyone see the Bug in the sites you Pokesniper Recommends for us to snipe.... Not complaining 
Nice effort Pokesniper to fix these bugs, Congrats!!!

**Comment by pokesniperandroid** [comment]
Well, if you happen have more sites that shares pokemon coordinates, don't hesitate to share.
About IV, i don't know why it's differ with PokeSniper but the IV parameter calculated from the API.
And for no more pokemon, i think if N people has been sniping those pokemon(s), there's probability that pokemon is gone or despawned.

**Comment by hpham1119** [comment]
Samuel, 

Excuse my language but for the past 24 hours all you have done it's bitch and bitch. Stop for 3 seconds and actually think about the amount of work it takes to run this app and cords website. And the fact that your able to use it for free. So stop complaining the moment your worthless pos that is laying on his bed doing nothing but sniping Pokemon can't catch anymore Pokemon the easy way. How about you be greatful a team is working on countering all the measures and securities the real Pokemon go app has in place so we can continue to cheat the system.

**Comment by MrCrunchy** [comment]
http://www.mypogosnipers.com/# I use this when pokezz is down. There's also a discord channel that posts live coordinates if you're interested in that as well let me know.

**Comment by pokesniperandroid** [comment]
@MrCrunchy i'm adding it to list
