### ISSUE TITLE
Sniper using only ultra balls

### ISSUE THREAD

**Issue by JayeshParekh1996** [pokesniperandroid/PokeSniper-Android#132]
Even for low levels of CP or IV the sniper is using only ultra balls.

**Comment by pokesniperandroid** [comment]
We've been introducing pokeball options a long time ago, but there's report the catch always fail so we remove it. Maybe in the next update we will add it again after tests.

**Comment by JayeshParekh1996** [comment]
I get it. Thanks for providing a great app
