### ISSUE TITLE
Use pinap berries option

### ISSUE THREAD

**Issue by kingkai808** [pokesniperandroid/PokeSniper-Android#133]
Pinaps give 2x candy so sniping with those berries are awesome if it could be implemented in the next update to farm those caddies faster!

**Comment by pokesniperandroid** [comment]
@kingkai808 probably will be added to next release with option to choose berry to use

**Comment by pokesniperandroid** [comment]
Try the new update v1.5.7-BETA1

**Comment by pokesniperandroid** [comment]
@kingkai808 is there any bug(s) you encounter in new berry feature? if not, i'll close this issue?

**Comment by kingkai808** [comment]
I'm testing it. But it seems the pinap berry if 0 are in inventory then it doesn't revert to your next berry. But I also am getting a lot of no more poke to catch. When I know they are there as its caught on another account with plenty of time. Again not sure if berry related.

**Comment by pokesniperandroid** [comment]
what do you mean about revert to next berry?
about no more pokemon to catch, is it happen to all account or some?

**Comment by kingkai808** [comment]
If you run out of certain berry, it doesn't automatically use the next berry in stock.
And it happens on only certain accounts and then it rotates. I'll have to spoof and snipe it with GPS that's how I know the poke is really there.

**Comment by pokesniperandroid** [comment]
well, maybe we'll add switch option to automatically use in-stock berry if choosen berry run out. for the current release, only choosen berry used, so if its run out then no berries to use.

as no more pokemon, could happen because delayed response when calling map update after moving coordinate. will try to test it to know certain amount time to wait map update.

**Comment by Av1s** [comment]
guys remember to close the issues when it is sorted out...@kingkai808
