### ISSUE TITLE
Pokebag crash

### ISSUE THREAD

**Issue by Qubson** [pokesniperandroid/PokeSniper-Android#134]
When i click pokebag and choose accounts, app crashing

**Comment by SamuelPGM** [comment]
Yeah, happening to me also, but mine doesn't crash, it just doesn't load up, which for me was alright, but now it have this bug.

**Comment by pokesniperandroid** [comment]
API is broken as of today. Need to wait for API fixes.

**Comment by pokesniperandroid** [comment]
#141
