### ISSUE TITLE
Experimental 6 - Request to server couldn't be started, please try again

### ISSUE THREAD

**Issue by samchoi02** [pokesniperandroid/PokeSniper-Android#135]
When i press 'Snipe those bitches' It's keep saying 'Request to server couldn't be started, please try again'

**Comment by SamuelPGM** [comment]
On Experimental 4 also has that... I think is happening to everybody

**Comment by SamuelPGM** [comment]
Shit.... I've updated experimental 4 to Experimental 6 to see if it changed it... but nothing !!!
Godamnit pokesniper.... everything was alright this morning but now a new bug has arrived!
Solve it now!
Thanks.
-Samuel

**Comment by KHARUROSU** [comment]
Niantic made some changes to the API today. There is a need to data-mine it first, before fixing this APP. Wait a few days guys, pokesniper always solves the problems.

**Comment by pokesniperandroid** [comment]
API is broken as of today. Need to wait for API fixes.

**Comment by pokesniperandroid** [comment]
#141
