### ISSUE TITLE
All Experimentals are having the following Bug :

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#136]
"REQUEST TO SERVER COULDN'T BE STARTED, PLEASE TRY AGAIN"

At least on Experimental 4 and 6, these error is appearing.

Pokesniper, there is not reason that this is happening, early this morning I was Sniping normal.... try to fix SOMETHING THAT WAS ALREADY FIXED please (BTW, THE REQUEST TO SERVER BUG WAS ALREADY HAPPENING, I FIRST NEEDED TO SNIPE ONCE AT THE SAME POKÉMON, SO THAT THIS ERROR MESSAGE COULD SHOW UP, SO THEN, I COULD SNIPE TWICE AT THE SAME POKEMON SO THATHAT EVERYTHING WAS ALL RIGHT , AND THAT REQUEST ERROR WAS MAKING ME SEE MORE ADDS!!!)..

**Comment by KHARUROSU** [comment]
Niantic made some changes to the API today. There is a need to data-mine it first, before fixing this APP. Wait a few days guys, pokesniper always solves the problems.

**Comment by pokesniperandroid** [comment]
#141
