### ISSUE TITLE
Pokebag isn't loading !

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#137]
Everything was fine this morning: My Pokebag was all right, and so was the Sniper button! 
But now in the night I can't open my Pokebag, and neither I can Snipe!

**Comment by SamuelPGM** [comment]
I was on Experimental 4 and got to 6, to see if something would change, but it did not!

**Comment by SamuelPGM** [comment]
"REQUEST TO SERVER COULDN'T BE STARTED, PLEASE TRY AGAIN"
that's the reason I can't snipe now....

**Comment by KHARUROSU** [comment]
Niantic made some changes to the API today. There is a need to data-mine it first, before fixing this APP. Wait a few days guys, pokesniper always solves the problems.

**Comment by pokesniperandroid** [comment]
As @KHARUROSU also stated, API is broken as of today. Need to wait for API fixes.

**Comment by pokesniperandroid** [comment]
#141
