### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by karla1230** [pokesniperandroid/PokeSniper-Android#139]
Request to server couldn't be started,  please try again

**Comment by karla1230** [comment]
I think everyone experiences the same thing.
????

**Comment by pokesniperandroid** [comment]
API is broken as of today. Need to wait for API fixes.

**Comment by elviri** [comment]
The api 0.45 to disappear from the game, that is why it leaves the error of not communicating with server.
Pokesniperandroid works fine if in settings you use Api Hash Key, I have one and it works fine

**Comment by pokesniperandroid** [comment]
#141
