### ISSUE TITLE
PokeSniper no longer work until API Update

### ISSUE THREAD

**Issue by pokesniperandroid** [pokesniperandroid/PokeSniper-Android#141]
<b>Bugs</b>
- Failed to send request which flagged as SESSION_INVALIDATED as Niantic blocked 0.45 login

<b>Workaround</b>
-Fixed in v1.5.6
<br />

- <b>To be safe, stop sniping because you could get banned because request is not valid.</b>
- <b>Hash key users can snipe as usual</b>

**Comment by Arun12121** [comment]
Will you guys be able to fix it?

**Comment by hpham1119** [comment]
Give them time. Be patient

**Comment by pokesniperandroid** [comment]
Update released, please try it.

**Comment by pinkha8er9989** [comment]
@pokesniper i love your work man much love. I am getting the following error [svarzee.gps.gpsoauth.Gpsoauth
$tokenrequestfailed]

**Comment by SuperDuper77** [comment]
Still not opening my bags on note2

**Comment by pokesniperandroid** [comment]
@pinkha8er9989 try with PTC account, sometimes google block login request
@SuperDuper77 did you try with another account? or the result all same?

**Comment by pinkha8er9989** [comment]
I tried with my PTC account and it reports the same error

**Comment by pinkha8er9989** [comment]
Do you run pokezz might i ask? If so id like to make a donation if not how else could i make a donation :) mahalo

**Comment by andy1688878** [comment]
It work 😀

**Comment by pinkha8er9989** [comment]
And i apolagize i set my ptc to google account within the sniper app. My fault. My ptc account has to be verified takes up to 24 hours

**Comment by 13nour** [comment]
It doesn't work with my Google account , error : d.a.a.c$a

**Comment by SamuelPGM** [comment]
Not happening to me

**Comment by SamuelPGM** [comment]
And I use both Ptc And Google

**Comment by pinkha8er9989** [comment]
I recieved both errors on sepperate instances

**Comment by sandstorm267** [comment]
new error:
keeps saying no more POKEMON to catch
i kept trying 
Could you please look int it?

**Comment by sandstorm267** [comment]
ignore what i said my pokedex was full everything is fine. sorry

**Comment by SamuelPGM** [comment]
Lol, you should say thanks and sorry to pokesniper! Lol

**Comment by chimsedinang123** [comment]
Thank pokesniper team has released the best products to users.

but I do not see the error on the test to be overcome

- Application crashes when opening the bag pokemon

- Has added a new fruit

 - The display of CP and the fourth is not good

 Thank pokesniperandrois

**Comment by chimsedinang123** [comment]
Pokesniperandrois ..Request to the server could not be replied to, please try again '. This error occurred in the official version 1.5.6.

 Hope will troe the earliest pokesniper

**Comment by pokesniperandroid** [comment]
@pinkha8er9989 i'm not running pokezz and can you elaborate about error on separate instances
@13nour try with PTC account, google sometimes block login request
@chimsedinang123 this release for API fix only for now
and for Request to server could not be repliet, probably you need to try again or try with different account.
PokeBag crash probably caused by different way of handling activity on specific devices, will try to investigate

for new fruits still WIP because we need to modify the API so the app can choose the item to use when catching pokemons, no ETA

**Comment by pokesniperandroid** [comment]
Try the new update v1.5.7-BETA1

**Comment by chimsedinang123** [comment]
Pokesniper : 

×

TẤT CẢ

TIN TỨC

HÌNH ẢNH

VIDEO

SÁCH

CÁC CÔNG CỤ TÌM KIẾM

Google Ads Việt Nam - Google.com.vn‎

QCwww.google.com.vn/AdWords‎

Thu hút thêm khách hàng tiềm năng & khách hàng mới vào website của bạn.

Appear On Google Search · Sign Up Today

Bắt đầu với AdWordsĐặt ngân sách của bạnMẹo để thành côngAdWords Căn Bản

Google Dịch‎

QCGoogle Play: 4,4 (4,8 Tr)‎

Sử dụng máy ảnh để dịch văn bản. Tải ứng dụng Dịch trên Android

MIỄN PHÍ

Tải xuống từ Google Play

Cảm ơn nhóm pokesniper. Tôi sẽ chạy thử ngay bây giờ . có thông tin cho rằng API0.45 đã hồ... Thêm

---------------Phát hiện ngôn ngữTiếng Ả RậpTiếng AfrikaansTiếng AlbaniaTiếng AmharicTiếng AnhTiếng ArmeniaTiếng AzerbaijanTiếng Ba LanTiếng Ba TưTiếng BanglaTiếng BasqueTiếng BelarusTiếng BosniaTiếng Bồ Đào NhaTiếng BulgariaTiếng CatalanTiếng CebuanoTiếng CorsicaTiếng CroatiaTiếng Do TháiTiếng Đan MạchTiếng ĐứcTiếng EstoniaTiếng FilipinoTiếng FrisiaTiếng Gael ScotlandTiếng GalicianTiếng GruziaTiếng GujaratiTiếng Hà LanTiếng HaitiTiếng HànTiếng HausaTiếng HawaiiTiếng HindiTiếng HmongTiếng HungaryTiếng Hy LạpTiếng IcelandTiếng IgboTiếng IndonesiaTiếng IrelandTiếng JavaTiếng KannadaTiếng KazakhTiếng Khơ-meTiếng KurdTiếng KyrgyzTiếng La-tinhTiếng LàoTiếng LatviaTiếng LitvaTiếng LuxembourgTiếng Mã LaiTiếng MacedoniaTiếng MalagasyTiếng MalayalamTiếng MaltaTiếng MaoriTiếng MarathiTiếng Miến ĐiệnTiếng Mông CổTiếng Na UyTiếng NepalTiếng NgaTiếng NhậtTiếng NyanjaTiếng PashtoTiếng PhápTiếng Phần LanTiếng PunjabTiếng Quốc Tế NgữTiếng RomaniaTiếng SamoaTiếng SécTiếng SerbiaTiếng ShonaTiếng SindhiTiếng SinhalaTiếng SlovakTiếng SloveniaTiếng SomaliTiếng Sotho Miền NamTiếng SundaTiếng SwahiliTiếng TajikTiếng TamilTiếng Tây Ban NhaTiếng TeluguTiếng TháiTiếng Thổ Nhĩ KỳTiếng Thụy ĐiểnTiếng Trung (Giản Thể)Tiếng Trung (Phồn thể)Tiếng UcrainaTiếng UrduTiếng UzbekTiếng ViệtTiếng WalesTiếng XhosaTiếng ÝTiếng YiddishTiếng YorubaTiếng ZuluTiếng Việt

Thank pokesniper group. I'll run it now. there is news that has revived API0.45. Is that so ?

---------------Tiếng Ả RậpTiếng AfrikaansTiếng AlbaniaTiếng AmharicTiếng AnhTiếng ArmeniaTiếng AzerbaijanTiếng Ba LanTiếng Ba TưTiếng BanglaTiếng BasqueTiếng BelarusTiếng BosniaTiếng Bồ Đào NhaTiếng BulgariaTiếng CatalanTiếng CebuanoTiếng CorsicaTiếng CroatiaTiếng Do TháiTiếng Đan MạchTiếng ĐứcTiếng EstoniaTiếng FilipinoTiếng FrisiaTiếng Gael ScotlandTiếng GalicianTiếng GruziaTiếng GujaratiTiếng Hà LanTiếng HaitiTiếng HànTiếng HausaTiếng HawaiiTiếng HindiTiếng HmongTiếng HungaryTiếng Hy LạpTiếng IcelandTiếng IgboTiếng IndonesiaTiếng IrelandTiếng JavaTiếng KannadaTiếng KazakhTiếng Khơ-meTiếng KurdTiếng KyrgyzTiếng La-tinhTiếng LàoTiếng LatviaTiếng LitvaTiếng LuxembourgTiếng Mã LaiTiếng MacedoniaTiếng MalagasyTiếng MalayalamTiếng MaltaTiếng MaoriTiếng MarathiTiếng Miến ĐiệnTiếng Mông CổTiếng Na UyTiếng NepalTiếng NgaTiếng NhậtTiếng NyanjaTiếng PashtoTiếng PhápTiếng Phần LanTiếng PunjabTiếng Quốc Tế NgữTiếng RomaniaTiếng SamoaTiếng SécTiếng SerbiaTiếng ShonaTiếng SindhiTiếng SinhalaTiếng SlovakTiếng SloveniaTiếng SomaliTiếng Sotho Miền NamTiếng SundaTiếng SwahiliTiếng TajikTiếng TamilTiếng Tây Ban NhaTiếng TeluguTiếng TháiTiếng Thổ Nhĩ KỳTiếng Thụy ĐiểnTiếng Trung (Giản Thể)Tiếng Trung (Phồn thể)Tiếng UcrainaTiếng UrduTiếng UzbekTiếng ViệtTiếng WalesTiếng XhosaTiếng ÝTiếng YiddishTiếng YorubaTiếng ZuluTiếng Anh

Phản hồi

Hoán đổi sang Tiếng Việt

Thank pokesniper group. I'll run it now.

there is news that has revived API0.45. Is that so ?

**Comment by chimsedinang123** [comment]
Thank pokesniper group. I'll run it now.

there is news that has revived API0.45. Is that so ?

**Comment by pokesniperandroid** [comment]
@chimsedinang123 0.45 has ben fixed in 1.5.6

**Comment by SuperDuper77** [comment]
Finally with new 1.5.7 beta can open my bags TQ
