### ISSUE TITLE
Error on "request to server couldn't be started, please try again"

### ISSUE THREAD

**Issue by emanuelebixx** [pokesniperandroid/PokeSniper-Android#142]
Any idea what I'm doing so wrong? 

[15:04:51] Trying login with Google...
[15:04:53] Request to server couldn't be started, please try again

**Comment by MrCrunchy** [comment]
Read previous posts before posting plz. API needs update. Wait or keep trying.

**Comment by pokesniperandroid** [comment]
refer to #141

**Comment by pokenato** [comment]
Hey dear, i have the same error, have a estimated date to fix To have a mãe version?
