### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ecg3500** [pokesniperandroid/PokeSniper-Android#145]
Downloaded the newest version. Set it to start snipe and it said need to enter captcha. Now whenever I log into Pokemon go I get a screen with the pokemongo logo at the top and a blank white screen with no place to enter captcha. Deleted the app. Changed password, uninstalled go reinstalled multiple times. Message STILL shows up.    [http://imgur.com/a/6BmKQ](url)

**Comment by pokesniperandroid** [comment]
I need to ask, why did you open the Pokemon GO app to enter captcha? PokeSniper handle captcha request by displaying captcha form in a popup (inside PokeSniper). You won't need to open Pokemon GO app when using PokeSniper.

**Comment by ecg3500** [comment]
i never got the popup. so i figured i needed to go into the app to do so. Have you ever seen this happen before?

**Comment by pokesniperandroid** [comment]
This never happen before, try uninstall PokeSniper and install again. Create new PTC account and try use it. Check the popup is showing or not when asked to enter captcha.

And last, if you don't mind, what is your device model and android version?

**Comment by ecg3500** [comment]
Galaxy s6 edge sm-g925a. Android version 6.0.1 this was done on my Google act. I'll try and set up a new PTC account now and see what happens

**Comment by ecg3500** [comment]
http://imgur.com/a/VenIu.  Captcha phrase didn't even show up this time with PTC test account

**Comment by ecg3500** [comment]
http://imgur.com/a/W6pyz. Ok this time on test PTC white box with the word "captcha" popped up. I clicked it and it successfully passed

**Comment by ecg3500** [comment]
http://imgur.com/a/ZiLGE.  Tried testing it on my Google account. This is the message I receive now when attempting to start snipe

**Comment by ecg3500** [comment]
same thing happens on my ptc account now.... same white box when attempting to log in

**Comment by pokesniperandroid** [comment]
okay, the first image means ok exept the wrong password and couldn't be started (can be tried again).
as for second image it asking for captcha, but you didn't get popup and you logged in just fine
third image is login request is blocked by google.

so the conclusion is that you can use just fine when you received message about login succeed, as for google account this happen sometimes and can't be avoided because the control is on google.

for white box on Pokemon GO app, try to force stop PokeSniper first then try to login to official app.

**Comment by ecg3500** [comment]
Force stopped pokesniper. Went into Pokemon go. White box still pops up. I can scroll up and down and left and right within the white box buts there's no text anywhere. 

Then tried uninstalling pokesniper, reinstall Pokemon go and both my original Google account and my test PTC account both have the same white box now

**Comment by ecg3500** [comment]
Created new PTC account. Works just fine. No white box

**Comment by pokesniperandroid** [comment]
probably your account was flagged by niantic

**Comment by ecg3500** [comment]
so im just SOL now?

**Comment by pokesniperandroid** [comment]
well, this never happen before. we use both pokesniper and pokemon go at same device and run just fine. probably test it using emulator in PC such as Nox, Bluestack or Genymotion to snipe.

**Comment by ecg3500** [comment]
tried nox and bluestacks. On emulators it says "unable to authentic" never had an issue with spoofing until i download this. now any account info i type into pokesniperandroid i get the whitescreen for.. no text. this sucks

**Comment by ecg3500** [comment]
lvl 33 account with 210 different pokes caught. is just gone. any possibility of this issue just disappearing after a few days?

**Comment by pokesniperandroid** [comment]
we don't really know because this issue never happen. using third party app bound to be banned (either soft ban or perma ban). if an account get banned, there should be an email contain the ban reason.

**Comment by pokesniperandroid** [comment]
try login with different device (real device)

**Comment by ecg3500** [comment]
good call dude! logged in on my gfs phone. at first it did the same thing... then magnemite popped up the the captcha box. clicked it and got right in! thanks man. sry probably wont be using your sniper again just to be on the safe side. haha, but i appreciate the assist with troubleshooting

**Comment by ecg3500** [comment]
im guessing since i went into the app while sniper was running it triggered the captcha box to be blank somehow. hope that helps with your testing

**Comment by pokesniperandroid** [comment]
well, thats good then. sorry for the inconvenience our app may cause you.

probably duplicate login detected as pokesniper and pokemon go asking same request.

**Comment by ecg3500** [comment]
my mock locaation button in dev options has disappeared now. still have the app i was using previously for spoofing but the on/off button for allow mock has disappeared. any idea?

**Comment by pokesniperandroid** [comment]
i don't know, our app didn't use mock location from android. try restarting the phone.
