### ISSUE TITLE
Request to server couldn't be started, please try again

### ISSUE THREAD

**Issue by xiaoming93** [pokesniperandroid/PokeSniper-Android#146]
Has been happening since last night, any solutions?? Thank you in advance

**Comment by pokesniperandroid** [comment]
Sorry for late response. Which version were you using? If you use v1.5.6 or 1.5.7-BETA1 this probably the app can't start the operation. Force stop the app and try again. Try with another account too to check whether the error operation(s) happen in one account or any given account.

**Comment by xiaoming93** [comment]
Hi I'm using the latest one, 1.5.7 beta1. Tried the mentioned methods and did not work. Guess I'll wait for the next version

**Comment by xiaoming93** [comment]
Update problem solved by reinstall ing. Thank you

**Comment by xiaoming93** [comment]
Update problem solved by reinstall ing. Thank you
