### ISSUE TITLE
Pokesniper

### ISSUE THREAD

**Issue by ryanbks8000x** [pokesniperandroid/PokeSniper-Android#147]
Keeps saying "no more "insert pokemon name" to catch" every time. If you can fix this please

**Comment by MrCrunchy** [comment]
That typically means you were to slow and the pokemon was no longer there.  Are you using pokezz for coordinates?

**Comment by ryanbks8000x** [comment]
Im using, lots of different maps, to get coordinates, and up until today,
it kept saying no more of this pokemon

**Comment by MrCrunchy** [comment]
Try a fresh install.  I haven't had any problems but often a reinstall fixes things.

**Comment by ryanbks8000x** [comment]
That was after a fresh install

**Comment by pokesniperandroid** [comment]
@ryanbks8000x which version? please try both v1.5.6 and v1.5.7-BETA1 with multiple account to tests if you don't mind

**Comment by ryanbks8000x** [comment]
On a different account, it worked, but thats weird cuz my other account isnt banned, i just checked now

**Comment by ryanbks8000x** [comment]
Different account worked actually

**Comment by pokesniperandroid** [comment]
@ryanbks8000x yeah, probably flagged by Naintic, will try to investigate.

**Comment by ryanbks8000x** [comment]
Thanks

**Comment by ryanbks8000x** [comment]
I feel so dumb, i think it kept saying no more to catch, cuz my pokemon inventory was full. Lmao

**Comment by pokesniperandroid** [comment]
@ryanbks8000x well, maybe we'll add function to check whether the pokebag is full or not on the next update

**Comment by ryanbks8000x** [comment]
That would be good thanks again
