### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by shugoamu** [pokesniperandroid/PokeSniper-Android#148]
Thank you for your effort  on this app, it can now be used smoothly. Just one problem has been met,  Captcha popped up but failed to verify due to crashes. It crashed everytime when I tried to pass the captcha test.

**Comment by pokesniperandroid** [comment]
when crashing, is send log popup appear or not?

**Comment by shugoamu** [comment]
It seems it didn't appear...sometimes the app closes automatically, but sometimes the system of my phone(samsung s2) said that the apps had no response and ask if I would like to wait or close the app. when I restart the app, it doesn't ask me to send log.

**Comment by kingkai808** [comment]
I have the same problem except my pokefarmer hash # isn't working. I still have to manually solve them. Weird

**Comment by pokesniperandroid** [comment]
@shugoamu i thnik your device have different way of handling activity. workaround <b>probably</b> use pokehash key. if you want to, i can lend mine to test it first. 

@kingkai808 the pokefarmer endpoin seems changed, try BETA6
