### ISSUE TITLE
 The account lockout

### ISSUE THREAD

**Issue by chimsedinang123** [pokesniperandroid/PokeSniper-Android#150]
The account lockout is ongoing. Pokesniper 1.5.7 beta Is it safe for us? Because I know there are a few that have not been jailbroken API source 100%. They have launched to sell key.

Examples: team bossland

**Comment by chimsedinang123** [comment]
Pokesniperandroids help

**Comment by MrCrunchy** [comment]
Use at your own risk just like anything. To clarify though, this is not a bot program in the typical sense. The bans have been primarily for auto poke stop auto catch power leveling. What this app does is different.  It GPS spoofs to the pokemon, engages the pokemon, then returns you to your home location prior to throwing a poke ball. This technique has not led to permanent bans only soft bans typically if your home coordinate are not inputted correctly.

**Comment by pokesniperandroid** [comment]
As @MrCrunchy stated, there's no perma ban case so far. And PokeSniper only support key from PokeFarmer.

read https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer
