### ISSUE TITLE
Catching bug

### ISSUE THREAD

**Issue by klayscott** [pokesniperandroid/PokeSniper-Android#152]
Hi there first thanks for the amount of time u guys invest to make each version better than the last , but the latest version gives no more pokemon to catch even if the remaining time of the pokemon is still active , thanks for the help

**Comment by ryanbks8000x** [comment]
I have the same problem

**Comment by pokesniperandroid** [comment]
Try BETA5, should fixed this issue

**Comment by ryanbks8000x** [comment]
It worked thanks!

**Comment by klayscott** [comment]
It didnt for me should i keep beta4 and install the update beta5??

**Comment by pokesniperandroid** [comment]
@klayscott if you're using BETA4, just install BETA5

**Comment by klayscott** [comment]
Yes i just did it logged in just fine but it freezes at pokemon in sight:1 now...

**Comment by pokesniperandroid** [comment]
@klayscott what do you mean freeze? the app not responding or there's no log printed after that?

**Comment by Av1s** [comment]
@pokesniperandroid yeah... in the new beta 5 it sniped only 1 pokemon for me and then when i would try to snipe any other pokemon the log says... pokemon in sight:1... then it would stuck there for 5 sec. and then the advertisement would pop up.... it won't snipe any pokemon.... plz sort out this bug ASAP..... thanks

**Comment by pokesniperandroid** [comment]
force stop the app and try again
if the ad show up but the log didn't finish, probably the operation <b>interrupted</b> because the logs is subscribing to the event(s) of the sniping. 

interrupted in android could be caused by many reason, network, OS itself, etc

<img src="http://i.imgur.com/qKOh03B.jpg" width="50%">

**Comment by klayscott** [comment]
What @av1s said ! Thats the problem

**Comment by pokesniperandroid** [comment]
@klayscott do you mind provide screenshot?

**Comment by klayscott** [comment]
@pokesniperandroid you were right its a connection issue now it working perfectly thanks , ill close this issue , appreciate the effort
