### ISSUE TITLE
IMPORTANT SUGGESTIONS 

### ISSUE THREAD

**Issue by Av1s** [pokesniperandroid/PokeSniper-Android#155]
1.There should be a device emulating option... that means that we should be able to choose the device id , brand name etc.. it will make the app more secure... niantic can pick up that a player is using several different devices to play and so the id can be flagged.
2.There should be space to tell the nick name of pokémon in the bag and starred pokémons should also be indicated properly...

i just want the 1st option the 2nd is just and enhancement... hope u include the device emulating option in the new update.@pokesniperandroid

**Comment by pokesniperandroid** [comment]
as 1st, the app using device info by using android properties like software & hardware info. but, probably will add function to edit in the future. so, every user who use our app will use their own device information.
as 2nd, we'll try
