### ISSUE TITLE
Catch bug "pokemon in sight" 

### ISSUE THREAD

**Issue by jazzmaxi** [pokesniperandroid/PokeSniper-Android#156]
When I look for a pokemon it stays in sight and does not catch it, is it a Beta 6 bug?

**Comment by pokesniperandroid** [comment]
workaround, try one by one
1. change account
2. change network
3. force stop and retry

and please report the result if you still get same error

**Comment by jazzmaxi** [comment]
Still not working :( please solve it in the next update, this app was great

**Comment by pokesniperandroid** [comment]
what is the result? the log in app.

**Comment by jazzmaxi** [comment]
Hahaha sorry, it was because I had the pokemon box full, I love this app, thanks a lot for responding

**Comment by supergerman** [comment]
It still does nor catch pokemon, although they are in sight. Please help.

**Comment by tamoknhba** [comment]
Same here. Will not catch Pokemon. Says there in sight, then force stops right after... I've donated so please help or fix

**Comment by tamoknhba** [comment]
Was working on beta 7 now doing same thing and not working... Very upset I just missed a unown because of it...
