### ISSUE TITLE
d.a.a.c$a

### ISSUE THREAD

**Issue by xiaoming93** [pokesniperandroid/PokeSniper-Android#157]
Hi may I know if this app supports Xiaomi redmi 4A. I downloaded it but whenever I initiate catch it says trying login with Google, then next message shows "d.a.a.c$a" and it stops there

**Comment by pokesniperandroid** [comment]
workaround, try one by one
1. follow guide by google at https://support.google.com/accounts/answer/185833?hl=en
2. change account

and please report the result if you still get same error

**Comment by xiaoming93** [comment]
Hi but I am able to use it with no issues on my other Android phone and is also able to sign in my google accounts on my Xiaomi phone

**Comment by pokesniperandroid** [comment]
Yeah, this happen when google block login request because new device information. Try with PTC account if you dont mind. Create app password on google should fix this issue on many users (1st workaround) though

**Comment by idebojit** [comment]
Its due to the 2-Step verification for Google login.
Disable it. Worked for me :)
