### ISSUE TITLE
Stops after saying 4 pokemon in sight and will not catch any pokemon.

### ISSUE THREAD

**Issue by tamoknhba** [pokesniperandroid/PokeSniper-Android#158]
It starts fine, I just donated, so I'm a little peeved, so it starts, logins into Google, the says pokebank 9
Pokemon in sight, 4
Then nothing, and the snipe button refreshes.... Please help or please refund me so I can use this.... Is it supposed to catch gen 2 Pokemon as well???

**Comment by tamoknhba** [comment]
UPDATE:
added another account, and logged into mobile network, caught one pokemon, switch back to other account, then continued to stop after Pokemon in sight. Tried another Pokemon with account that caught the one, and does the same now as the other account, tried adding a third account, still same issue....

**Comment by tamoknhba** [comment]
NEW UPDATE:
worked again once on the account it worked on first, but now won't again. Also, the first account is now saying for every snipe, 0 Pokemon in sight....

**Comment by pokesniperandroid** [comment]
So, the operation is interrupted on pokemon insight, right? What accounts did you use except first account. Did you try with PTC account? We'll try track and find this issue ASAP. If you're still want refund, we'll happy to oblige. Just drop us an email to our paypal email that you've sent donation to.

**Comment by tamoknhba** [comment]
Yes exqctly. It stops right after it says pokemon in sight.  Accounts used like do you want me to give you the account login info or? Noooo I want the program to work lol... All accounts used where gmail account s I don't have PTC accounts... All mine are Google so if I can't get it to work with Google then I guess its not going to work for me...

**Comment by MrCrunchy** [comment]
Can you catch on normal program not pokesniper? The fact it worked on one but not another seems to imply a soft ban or out of poke ball?

**Comment by tamoknhba** [comment]
Nope no soft ban. It doesn't say Pokemon fled, it just simply stops running after Pokemon insight... It worked again on one account for one catch then stopped again...

**Comment by tamoknhba** [comment]
I've been sniping and hitting since the start of Pokemon go, and I know how and what a softban does and looks like... There's simply something wrong with the application where it stops running after Pokemon in sight....

**Comment by tamoknhba** [comment]
Botting*

**Comment by tamoknhba** [comment]
UPDATE: IF I LEAVE IT FOR AWHILE, I CAN CATCH ONE SINGLE POKEMONE, THEN IT WILL STOP AFTER IN SIGHT ON SECOND TRY. ONLY ONE ACCOUNT WILL WORK THO...

**Comment by MrCrunchy** [comment]
So lets assume no soft ban, pokemon aren't fleeing so you're saying it doesn't even attempt a catch? And your pokebag isn't full?  You have room to catch more?  You have poke balls? Did you try a fresh reinstall?

**Comment by tamoknhba** [comment]
Yes ive tried a fresh install. Ive tried multiple accounts. And yes, thats exactly what im saying. Obvipusly my pokebag isnt full as i said, ive been sniping for a long time now, yes i have pokeballs lol and i dont know how much clearer i can be.... It will not go any farther then pokemon in sight. It just stops and the snipe those bitches button refreshes.... Thats it thats all...

**Comment by pokesniperandroid** [comment]
@tamoknhba try BETA7 and please report

**Comment by tamoknhba** [comment]
Working now man. Cheers guys.
