### ISSUE TITLE
Same issue as before is now back. Stop after pokemon in sight. Will not catch

### ISSUE THREAD

**Issue by tamoknhba** [pokesniperandroid/PokeSniper-Android#159]
So everything was working great, now it keeps doing the same thing. Multiple accounts, multiple devices, doesn't matter, it stops right after Pokemon in sight.... Please help... I've missed out on so many Pokemon I've wanted because of this now....

**Comment by pokesniperandroid** [comment]
@tamoknhba did you try force stop the app and retry? change network?

**Comment by tamoknhba** [comment]
Yeah ive tried force closing. Unistall and reinstall. Tried different network. Everything I could think of man... Very frustrating...

**Comment by tamoknhba** [comment]
Like I said I even tried it on a different device....

**Comment by pokesniperandroid** [comment]
@tamoknhba try recent update BETA8 and report

**Comment by tamoknhba** [comment]
Working great. Thanks
