### ISSUE TITLE
failed to encounter (Pokemon name)

### ISSUE THREAD

**Issue by Chuyc022** [pokesniperandroid/PokeSniper-Android#160]
Shows me the Pokemon list but it always says "Failed to encounter..." Any help?

**Comment by pokesniperandroid** [comment]
Your account can not make encounter(s) to said pokemon. Encounter is like tapping pokemon before we can start catching/throwing ball in pokemon go app.

**Comment by vipulphenon** [comment]
Hey there,last 2 days I wont be able to catch any pokemon using this.
when I touched snipe those bitches it always show the message like this
request to server couldn't be started,please try again.
I did all things like cleared cache,data reinstalled reboot all.
but nothing is working.

**Comment by pokesniperandroid** [comment]
@vipulphenon check issue page before comment. refer #164

**Comment by fhanysyahrir** [comment]
Gmana caranya

Pada tanggal 9 Mar 2017 18.31, "pokesniperandroid" <notifications@github.com>
menulis:

**Comment by vipulphenon** [comment]
Thanks buddy for quick response.
Really appropriated your work.😃
