### ISSUE TITLE
update 0.57.4 androi pokemon go

### ISSUE THREAD

**Issue by chimsedinang123** [pokesniperandroid/PokeSniper-Android#161]
Following the update 0.57.4 pokemon go. John Hanke has interviewed: The company is planning to target the users cũng who ask for their fake GPS location to play the game while sitting on the sofa .. pokesniper có Is an emulator placement types. It has been banned?

**Comment by pokesniperandroid** [comment]
no at the moment

**Comment by kingkai808** [comment]
Is there a new update yet for the new api? I'll wait until a new api is out.

**Comment by pokesniperandroid** [comment]
there's no update for now

**Comment by cahyono2000** [comment]
Request to servers could not be started
Pogo 0.57.4

**Comment by pokesniperandroid** [comment]
#164
