### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chimsedinang123** [pokesniperandroid/PokeSniper-Android#163]
Today pokesniper error appeared " request to server couldn't be started ,please try again "

**Comment by chimsedinang123** [comment]
Pokesniper 1.5.7 beta1 , beta 8

**Comment by gdarya** [comment]
Same here. Please help

**Comment by chimsedinang123** [comment]
Pokesniperandroid help

**Comment by chimsedinang123** [comment]
Pokesniper must have been blocked by the new API version 0.57.4. Block simulation of placements. Should this lead to an error?

**Comment by pokesniperandroid** [comment]
#164
