### ISSUE TITLE
API Status - March 8, 2017

### ISSUE THREAD

**Issue by pokesniperandroid** [pokesniperandroid/PokeSniper-Android#164]
**Date**
- Mar 8, 2017

**Status:**
- API down

**Reason**
- Recent Pokemon GO update
- Failed to send request: SESSION_INVALIDATED

**Workaround**
- Wait API update

**Comment by samchoi02** [comment]
Hope to get fixed soon...Good Luck!

**Comment by klayscott** [comment]
Keep it up guys , and just for gigs niantic made 2 ban waves in a row

**Comment by Izan69** [comment]
How long is the update?

**Comment by mokenneth** [comment]
refer from other forum, Pokémon Go has started popping up a notice at launch which warns players who've used non-offical APP. they could lose their account if they don't stop asap.
![e88hjujsh2ky](https://cloud.githubusercontent.com/assets/22109429/23729062/e3d4420a-049a-11e7-983e-f9c3f46c62e5.jpg)
hope Pokesniper can solve this problem as well

**Comment by Kardshadow** [comment]
Im waiting for an update.. Thanks in advance, and keep up the good job

**Comment by kabirash** [comment]
Any further updates on a resolution to this issue as above?

Any update pokesniper.apk

**Comment by pokesniperandroid** [comment]
Not yet, the API still get same result SESSION_INVALIDATED. To be safe, just wait until API is normal again.
We can't risk to get banned because being impatient.

**Comment by gdarya** [comment]
You're the best

**Comment by xiaoming93** [comment]
I received that warning too... Guess time to stop sniping cuz I don't think they'll send a second one even if there's a long break

**Comment by kabirash** [comment]
Ive now received the same warning will i still get band ifi use official app. And go to location of pokemon via gps go and catch them.

**Comment by MrCrunchy** [comment]
Does no one read? Do not use this app until there's an update.  Other apps like poke++ you need to check with them if it's safe.  There are a lot of permanent bans going on right now.

**Comment by andamirorulez** [comment]
Why are you asking so rough??
If you dont want to wait, use something else...

**Comment by pokenato** [comment]
Hello guys, first of ali thank you for the effors to fix the Server error. 
If possible i'd like tô ask if have any stimated date to fix or have a new version? Thank you onde again.

**Comment by yiyonglee** [comment]
@mokenneth i got the same thing, and it keeps poping up everytime i relaunch the app. Not from pokesniperandroid app though, was because of IV GO app :(

**Comment by mokenneth** [comment]
@yiyonglee
 
just a warm alert to pokesniper to take into consideration for the next version development

**Comment by xeliman** [comment]
Please give a us a new version, I want to snipe those bitches

**Comment by pokesniperandroid** [comment]
try v1.5.7-BETA9

**Comment by Izan69** [comment]
Thank god...i can snipe those bitched..Thumbs up!!!

**Comment by Ashley567** [comment]
When I choose to autosnipe no pokemons are shown in sight. Plz help!!

**Comment by pokesniperandroid** [comment]
@Ashley567 can you provide more info than that? like where was the logs stopped at. if it says 0 pokemon, then either pokemon gone, the key is max (if use our shared key), or got softban. check via official pokemon go app.
