### ISSUE TITLE
Server couldn't be started

### ISSUE THREAD

**Issue by karla1230** [pokesniperandroid/PokeSniper-Android#166]
Request to server couldn't be started please try again

**Comment by fhanysyahrir** [comment]
[pokesniperandroid/PokeSniper-Android] Server couldn't be started (#166)

**Comment by fhanysyahrir** [comment]
Pada tanggal 9 Mar 2017 23.41, "karla1230" <notifications@github.com>
menulis:

**Comment by pokesniperandroid** [comment]
#164

**Comment by fhanysyahrir** [comment]
Hai,

Saya baru saja menandatangani petisi "Seluruh Warga Negara Indonesia:
100%in Indonesia Nyoblos" dan ingin tahu apakah Anda dapat membantu dengan
menambahkan nama Anda.

Tujuan kami adalah untuk mencapai 1.000.000 tanda tangan dan kami
membutuhkan dukungan lebih banyak. Anda dapat membaca lebih banyak petisi
dan menandatanganinya di sini:

http://chng.it/RSjZV2PpCb

Terima kasih!
Nurul fhany
