### ISSUE TITLE
 news up

### ISSUE THREAD

**Issue by chimsedinang123** [pokesniperandroid/PokeSniper-Android#167]
Pokebot has updated API 0.57.4 pokesniper have you not?

**Comment by dioargent** [comment]
Yah almost all pokebot work i see, and i just waiting ur update... 
Check gthub. Com/logxn/pokemongo-bot

**Comment by dioargent** [comment]
Yah almost all pokebot work i see, and i just waiting ur update... 
Check gthub. Com/logxn/pokemongo-bot

**Comment by pokesniperandroid** [comment]
There's new commit in API repo, but SESSION_INVALIDATED still showing up. You'll be notified if there's new update.

**Comment by Devil-Killer** [comment]
Why take so long time to release new Sniper...??

**Comment by SuperDuper77** [comment]
Better late than never lol.
