### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PhanindraGanesh** [pokesniperandroid/PokeSniper-Android#168]
Request to server couldn't be started please try again

**Comment by Alex5854** [comment]
Right !!!!

**Comment by fhanysyahrir** [comment]
Request to server couldn't be started please try again

Pada tanggal 11 Mar 2017 13.49, "Alex5854" <notifications@github.com>
menulis:

**Comment by pokesniperandroid** [comment]
#164 API not yet working

**Comment by fhanysyahrir** [comment]
Hai,

Saya baru saja menandatangani petisi "Menhub @BudiKaryaS, Turunkan harga
tiket pesawat domestik Indonesia." dan ingin tahu apakah Anda dapat
membantu dengan menambahkan nama Anda.

Tujuan kami adalah untuk mencapai 300.000 tanda tangan dan kami membutuhkan
dukungan lebih banyak. Anda dapat membaca lebih banyak petisi dan
menandatanganinya di sini:

http://chng.it/RbDVSRPBjB

Terima kasih!
Nurul fhany
