### ISSUE TITLE
What do you do when you try to snipe a Pokemon and it sends the message "request to server couldn't be started, please try again"?

### ISSUE THREAD

**Issue by uriahanium** [pokesniperandroid/PokeSniper-Android#170]

**Comment by pokesniperandroid** [comment]
API not working yet as 0.57.4 update. Don't use pokesniper until there's new update.

**Comment by xeliman** [comment]
Why are you taking so long to update pokesniper?

**Comment by andamirorulez** [comment]
Why are you asking so rough??
If you dont want to wait, use something else...

**Comment by xeliman** [comment]
I'm not saying it in a bad way, just asking

**Comment by kingkai808** [comment]
New api is out and working ATM. Pokesbuper probably hasn't got his hands on it yet.

**Comment by vipulphenon** [comment]
@kingkai808 where is new api give the link of it man.

**Comment by yiyonglee** [comment]
for now, while we wait patiently, donate @pokesniperandroid some beer for job well done so far

**Comment by pokesniperandroid** [comment]
update released v1.5.7-BETA9
