### ISSUE TITLE
No pokemons in sight

### ISSUE THREAD

**Issue by Ashley567** [pokesniperandroid/PokeSniper-Android#172]
While sniping no pokemons are shown in sight. At first I thought it might have been a softban but that's not so. Account is fine.

**Comment by pokesniperandroid** [comment]
Did you use our shared key or your own?

**Comment by lukmansyah** [comment]
"You need Pokehash key to snipe"
Why??? how to handle it ???

**Comment by Ashley567** [comment]
I used the shared key

**Comment by Ashley567** [comment]
I seems to be working after Beta10 update. Thank you and keep up the good work. Please make the updates free for us as of now. Thank you once again.
