### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by mejonma** [pokesniperandroid/PokeSniper-Android#173]
App crashes when attempting to catch Pokemon. Can't catch anything at the moment.

**Comment by pokesniperandroid** [comment]
Yeah, seems conflict with the berry options. Will push new update soon.

**Comment by pokesniperandroid** [comment]
Try BETA10

**Comment by MisterJohnHanke** [comment]
Still crashing Sir :(

**Comment by pokesniperandroid** [comment]
@MisterJohnHanke
What kind of crash you speak of? If when catching pokemon, it should have been fixed in BETA10.

**Comment by MisterJohnHanke** [comment]
Theres a pokemon in sight but it says "Failed to encounter pokemon"

**Comment by pokesniperandroid** [comment]
@MisterJohnHanke
Your account can't encounter the pokemon (it's when you tap the pokemon on Pokemon GO app before catching). Try with different account.

**Comment by MisterJohnHanke** [comment]
Hmmm no more failed to encounter, its just my bag is full but the app is still crashing sir. Kindly  try it.

**Comment by MisterJohnHanke** [comment]
What might be the cause of the problem sir?

**Comment by pokesniperandroid** [comment]
Okay. Do you mind to tell me where is the app crashed. Like trying to catch, open pokebag, add account, etc.

**Comment by MisterJohnHanke** [comment]
Something like this.

Pokemon in sight , magicarp, dragonair
Attempting to catch dragonair.

Then after that the app will close automatically sying "Pokesniper stopped"

**Comment by pokesniperandroid** [comment]
Version? Try disable berry, auto transfer, any options in setting then try again.

**Comment by MisterJohnHanke** [comment]
I just reinstall it and its working.. thank you sir. U know what.. ive been looking for ur app to be actve again since the early days of pogo.. i dnt know but i dnr exprience soft bans using this app.

**Comment by lukmansyah** [comment]
"You need Pokehash key to snipe"
Why??? how to handle it ???

**Comment by lukmansyah** [comment]
"You need Pokehash key to snipe"
Why??? how to handle it ???
whereas,i have try BETA 10

**Comment by MisterJohnHanke** [comment]
This app is so good, maker of pokesniper for andoid, how this app avoid softbans? Whre in fact i snipe 2 consecutive pokemons from far distances and i dnt get soft ban when i open the pogo app right away? Kudos.

**Comment by pokesniperandroid** [comment]
It's teleport to target then back to home.
