### ISSUE TITLE
No problem

### ISSUE THREAD

**Issue by Izan69** [pokesniperandroid/PokeSniper-Android#174]
No problem of catching it..

**Comment by MisterJohnHanke** [comment]
Still crashing sir

**Comment by Izan69** [comment]
Have u insert the hash key?

**Comment by MisterJohnHanke** [comment]
Yes.. what might be the cause of the problem

**Comment by lukmansyah** [comment]
"You need Pokehash key to snipe"
Why??? how to handle it ???
