### ISSUE TITLE
failed to encounter

### ISSUE THREAD

**Issue by fabioVeronese** [pokesniperandroid/PokeSniper-Android#178]
i am using the beta10 with de provided hash key. it was working ok but now the app finds the pokemon in sight , but then it says that it failed to enconter the same pokemon that was in sight. 

EDIT: with PTC it is working ok, but when i change to google acount it fail to encounter all the pokemons

**Comment by pokesniperandroid** [comment]
1. Check pokebank
2. Check softban in Pokemon GO app

**Comment by fabioVeronese** [comment]
the pokebank opens and it is not softbanned

**Comment by pokesniperandroid** [comment]
Sorry. I meant, the pokebank is full or not.  
As for softban, can you tap any pokemon in Pokemon GO app?

**Comment by fabioVeronese** [comment]
no the pokebank isn't full. and yes, it appeared to be normal in the app

**Comment by pokesniperandroid** [comment]
When the account couldn't encounter any pokemon, either pokebank full or softban. Both PTC and Google. Did you try with different pokemon?

**Comment by fabioVeronese** [comment]
yeah.. well, i will give it some time and try again later... then i repport to you... thanks a lot

**Comment by pinkha8er9989** [comment]
Report same error failure to encounter plenty of room in pokebag and not soft banned using hash key

**Comment by fabioVeronese** [comment]
I had noticed  that this error appears when there is 9 or less empty room in the pokebank... plz check it who has  this same problem.
