### ISSUE TITLE
Its  being fun 

### ISSUE THREAD

**Issue by klayscott** [pokesniperandroid/PokeSniper-Android#181]
@pokesniperandroid thanks for all the effort u guys putted in ! Niantic seems everything that have access to there server i mean anything ! I stopped using pokesniper way before the new update and still getting the warning message and never used any sniping tool or iv checkers , to sums it up i would never use anything that include my google accout login and put my main account at risk i suggest it to others to do the same ! Thank you for all the experience you've gave us

**Comment by pokesniperandroid** [comment]
Yeah, it's the risk to use third party apps (i meant any). Because the new update will flag any account using third party (maybe). I don't get it btw and still use it. Maybe you need create dummy account just to play with.
