### ISSUE TITLE
Add option to catch all pokemons 

### ISSUE THREAD

**Issue by Kardshadow** [pokesniperandroid/PokeSniper-Android#183]
Hi,  can you Add an option to catch all the pokemons found on one spot, it Will be awesome

**Comment by pokesniperandroid** [comment]
Okay, after some tests. This feature will get you softban because the encountered pokemon can only be one at a time (to avoid softban, because after encounter the pokemon we go back to home and catch it), so the rest of pokemon at that spot couldn't be captured because we were home.

**Comment by Kardshadow** [comment]
Understand,  thanks anyways 😀😀

**Comment by Kardshadow** [comment]
And thanks for this awesome app, good job
