### ISSUE TITLE
Failed to encounter

### ISSUE THREAD

**Issue by Herng97** [pokesniperandroid/PokeSniper-Android#184]
As the title said..I also noticed it only happend when there're two same pokemon at the location that are targeted after catching the first one the second one will always fail.But resniping it works..

**Comment by Vindil** [comment]
I've experienced the same thing. Also when it searches for a second Pokémon it can be quite a lengthy process when of course you don't even expect a second Pokémon to be there. It would be better if it didn't try to find another Pokémon at all in my humble opinion

**Comment by pokesniperandroid** [comment]
Yeah, PokeSniper currently catch any matched Pokemon. Will add option to pick catch one or catch all matched.
