### ISSUE TITLE
D.A.A.C$A

### ISSUE THREAD

**Issue by pinkha8er9989** [pokesniperandroid/PokeSniper-Android#185]
Only reports when using my ptc account. I can only use one account of my 4. The 3 googles accounts only one works reports failure to encounter and the 4 account is otc reports the above

**Comment by nsboption** [comment]
Me even Google account still occur this  D.A.A.C$A

**Comment by pokesniperandroid** [comment]
This error happen on Google account when the Google servers block the login request, probably 2-step verification. Try following method:
https://support.google.com/accounts/answer/185833?hl=en

**Comment by nsboption** [comment]
My gmail account doesnot enable 2-step verification

**Comment by xeliman** [comment]
Pinap berry doesn't work
