### ISSUE TITLE
Something that is unclear...

### ISSUE THREAD

**Issue by SamuelPGM** [pokesniperandroid/PokeSniper-Android#186]
So, when I got back to my pokemon account when the last update got released, I got that warning that my account was using third party apps, and that Niantic Expect us to stop using those, saying that accounts could be banned, I want someone that can confirm for me, that if after that warning, we still can use: Fly Gps (spoofers) or pokesniper (third application).... I need to know if I snipe one more time, I get banned, please, I'm not using third apps after this Niantic message, unless is safe to use 3apps and it's just a message to scare players .... 
Please don't close this issue until I reply! THANK YOU.
XD

**Comment by Kardshadow** [comment]
You amount is already flaged,  I would recommend stop using cheats

**Comment by pokesniperandroid** [comment]
Your account probably flagged, i think it's wise to change account rather than continue with the same account.

**Comment by MrCrunchy** [comment]
Flygps is the issue I'm guessing .  If you tap to go like you're actually walking or driving you won't get flagged. When you pop up around the globe you get almost an immediate flag.  Using just pokesniper I've gotten no issues or flags.
