### ISSUE TITLE
Pokehash key exception error

### ISSUE THREAD

**Issue by junaidsur** [pokesniperandroid/PokeSniper-Android#187]
Failed to perform  pokehash request

**Comment by kabirash** [comment]
Same problem her

**Comment by kabirash** [comment]
Iv deleted the temp hash key
Then attempted to snip without hash key
It gave n error that hashkey was required
Went back in to settings and re-entered same hash key and this has fixed it no error when sniping as above. Hope this helps

**Comment by kabirash** [comment]
Oh well worked for a bit now back same hashkey problem

**Comment by xeliman** [comment]
I have the same problem

**Comment by sapukasibersih** [comment]
Same problem

**Comment by xiaoming93** [comment]
Remedy please come soon,  all that 100iv lapras x. X

**Comment by Kristantoyussuf** [comment]
Same problem need hash key

**Comment by Yashhhh** [comment]
yeah.. same problem.. hope u new hash key asap..

**Comment by Herng97** [comment]
The problem i think is actually due to the fact the hash key can only hold 150 request per min.And this key is shared to everyone, so you might wanna consider buying your own hash key to solve this problem...

**Comment by Vindil** [comment]
I have my own key and i have the same problem

**Comment by Yashhhh** [comment]
@Herng97  no for sure... new update has come with probably new api so we need an update or new hash key.. i guess

**Comment by Herng97** [comment]
oh...then the only think we can do is wait...D:

**Comment by pokesniperandroid** [comment]
Hello,

Sorry for late response. We've been do some checking and we got the same result. Then after some search, we discover in pogodev forum that the SSL certificate was expired 23 March 2017 (we try to check SSL expiry and it's true). But this probably the only reason so far for this error. For now, just wait for more news regarding this issue.

More:
- https://talk.pogodev.org/d/333-pokehash-buddyauth-com-ssl-certificate-expired
- https://talk.pogodev.org/d/332-certificate-verify-failed

**Comment by pokesniperandroid** [comment]
The SSL has been renewed, it's working again now. Please try it again to check the results. Our ends seems fine now.

**Comment by chimsedinang123** [comment]
Thank you

**Comment by sapukasibersih** [comment]
Tq so much..love u babe..

**Comment by Yashhhh** [comment]
love u  endlessly... :*
