### ISSUE TITLE
Unfortunately, Pokesniper has stopped.

### ISSUE THREAD

**Issue by ebkeong** [pokesniperandroid/PokeSniper-Android#189]
At the start screen, once i input the co-ord , the app crashes with this message. Please help me. Thanks.

**Comment by pokesniperandroid** [comment]
Have you add account into app?  And is the coordinates valid?

**Comment by ebkeong** [comment]
I added in my PTC account. The status showed : Ready. The coordinates i punched in is valid too. But when i hit Snipe The Bxxxx, the app closed and the error message appeared. I only downloaded the apk. Didn't download the source.zip file. Could that be the reason? Sorry for the noob question. Also thanks for responding.

**Comment by pokesniperandroid** [comment]
Which version did you use? And did you insert pokehash key?

**Comment by Limes625** [comment]
Pokesniper,  how can I log in with 10 accounts? Just do donation?

**Comment by ebkeong** [comment]
I foubd the problem. If i use wifi at home, this problem occurs. When i switch to 4G in my cellphone, this sniper is a blessing to PoGo players. Thanks all for your support.
