### ISSUE TITLE
Low cp? 

### ISSUE THREAD

**Issue by superstarmie** [pokesniperandroid/PokeSniper-Android#19]
Catching these snipes got low cp pokemons? Is there anyway to catch high cp ones?

**Comment by myhadhy** [comment]
I have been researched, CP pokemons is pure random to every level of players, meaning it will be same for every players with same level. Example, you are lv 20 and all off players in the world which lv 20 will get same CP either it high or low. So, the app is really unrelated with your pokemons CP.

**Comment by pokesniperandroid** [comment]
if you want legit pokemons with high CP and IV, you may want to browse in Discord channel => https://discord.gg/GnKTcJm
because in website's list in PokeSniper App are not displaying IV or CP, you'll get random IV/CP from pokemon.
