### ISSUE TITLE
How can I do multiple accounts snipe

### ISSUE THREAD

**Issue by Limes625** [pokesniperandroid/PokeSniper-Android#190]
How can I do multiple accounts snipe

**Comment by pinkha8er9989** [comment]
Multi device

**Comment by Limes625** [comment]
Able to use multiple accounts in 1 phone thru ddnayion?

**Comment by Limes625** [comment]
Able to use multiple accounts in 1 phone thru ddnayion?

**Comment by Limes625** [comment]
Able to use multiple accounts in 1 phone thru donation?

**Comment by Limes625** [comment]
Able to use multiple accounts in 1 phone thru donation?

**Comment by MrCrunchy** [comment]
After capture Log out then in with another account but the pokemon will probably be gone by then.  Stop spamming.

**Comment by Limes625** [comment]
What is the best answer
