### ISSUE TITLE
Please for next update put a option to take pokestops

### ISSUE THREAD

**Issue by xeliman** [pokesniperandroid/PokeSniper-Android#193]

**Comment by Vindil** [comment]
You can't do that, it will get you soft banned

**Comment by xeliman** [comment]
No if you put coords of pokestops between your house

**Comment by MrCrunchy** [comment]
If it's between your house just walk there.  Auto spin apps already exist but require joystick mod like poke ++ there isn't a way to implement that here.

**Comment by Kaitlyn91** [comment]
If u want a way to snipe stops... Look up pokebot... Lot of settings but it does the job really well. They just updated it today as well. :)
