### ISSUE TITLE
Problems about Beta11 version

### ISSUE THREAD

**Issue by lessatio** [pokesniperandroid/PokeSniper-Android#196]
@pokesniperandroid 

- Berry throw still doesn't working
- Auto transfer is not working any longer (all rules tested)
- Login error with Google account, most of the time (SESSION INVALIDATED)
- After catch, not showning CP and IV Pokemon stats

**Comment by Herng97** [comment]
mine is showing cp and iv after catch...
and not yet get any error on google account login...

**Comment by kabirash** [comment]
Did get errors at first but has now faded out. And easy fix just snipe again. Where as before had to force close to snipe again. So billiant work. This temporary set back is no biggie

**Comment by Kaitlyn91** [comment]
Having issues with it taking forever to find a second pokemon to snipe. Usually it is on top of things, now it freezes.
