### ISSUE TITLE
 fruit   beta11

### ISSUE THREAD

**Issue by chimsedinang123** [pokesniperandroid/PokeSniper-Android#197]
Hello.

As the sniper is taking place. Soft newspapers used fruit (grape, banana, pineapple ....) but when entering the game to check the number of fruit in the bag does not change. Why so compassion?

  I use beta11

**Comment by lessatio** [comment]
@chimsedinang123 

Because it's not working properly.

**Comment by pokesniperandroid** [comment]
Berry issue seems came from the API level, will try to fix if possible
