### ISSUE TITLE
Poke balls

### ISSUE THREAD

**Issue by QBre** [pokesniperandroid/PokeSniper-Android#198]
by default, pokesniper uses Ultra Balls to snipe.
is there any way to change this?
I don't see it in the settings

nb: fruit still not working.

**Comment by pokesniperandroid** [comment]
Pokeball is picked automatically based on catch probability.

As for berry fruit, we'll try to fix it.

**Comment by QBre** [comment]
so this probability is based on the pokemon, CP, IV or all?
because it took 1 Ultra ball for a Gligar with low CP (150)...but IV 100%...

**Comment by QBre** [comment]
in v.13 fruits works well
poke ball selection also working.

great job!
