### ISSUE TITLE
Update 0.61.0 issues...

### ISSUE THREAD

**Issue by kkthedoc** [pokesniperandroid/PokeSniper-Android#202]
com.pokesniper.android.exceptions.request.RequestFailedException issue. Update related? Wait till further info/patch/update?

**Comment by Av1s** [comment]
@pokesniperandroid the niantic just forced 0.61.0 api... plz update the app ASAP.... 😊

**Comment by Av1s** [comment]
also add an option to select the type of ball which you want to use on for the catch just like the berry selecting module... add one for balls too.... keep up the good work

**Comment by Av1s** [comment]
also add an option to select the type of ball which you want to use on for the catch just like the berry selecting module... add one for balls too.... keep up the good work

**Comment by kkthedoc** [comment]
It auto updated mine. Though the Steelix gazing load screen is cool, if they've fixed any thing of interest to us is issue. Zat why that error?
