### ISSUE TITLE
0.61.0

### ISSUE THREAD

**Issue by chimsedinang123** [pokesniperandroid/PokeSniper-Android#207]
Today the banned waves have taken place. Whoever is like me, 2/4 account is locked

**Comment by QBre** [comment]
can you elaborate more....do you used pokesniper only or you do also some botting, gps spoofing etc.?
nothing happened to my account just yet.

**Comment by Biqueiras** [comment]
I use pokesniper and gps fly... banned too

**Comment by QBre** [comment]
if you spoof far away from your base, to other countries...I think that is the reason. I use gps fly up to 5km away from my home coordinate...and snipe only within my country base.

**Comment by Biqueiras** [comment]
Use in a city close... no rubber band (gps is off...) no jumps... :D

**Comment by QBre** [comment]
in that case...I'm waiting for my turn haha

did you received some warning before they banned you? usually there is.

**Comment by Biqueiras** [comment]
Yes,.,, the image saying to stop using third applications... but i use IVGO.. etc :D
Good luck to youu :D

**Comment by QBre** [comment]
aha...could be that IVGO is the thing...

**Comment by Biqueiras** [comment]
All ok, problems with the pokemon account :D
