### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by clockyyy** [pokesniperandroid/PokeSniper-Android#21]
Can't log into google account. Please help

**Comment by kingkai808** [comment]
Change password. Worked for me. Make it super easy

**Comment by clockyyy** [comment]
@kingkai808 i changed it 3 times. Still failed to login. :(

**Comment by pokesniperandroid** [comment]
check for ban through official app

**Comment by clockyyy** [comment]
My account not ban. Tried using my friend google acc, didn't work as well. Yup i set it to google. PTC works fine

**Comment by kingkai808** [comment]
I just used it. You have to disable 2 step verification and change the password to something easy.

**Comment by clockyyy** [comment]
@kingkai808 thank you! It works

**Comment by kingkai808** [comment]
Remember sniper every minute or you'll get soft banned very fast.

**Comment by sonofzaim** [comment]
Hi I'm having the same issue and I changed my password to the simplest I could (pass2016) and I have 2 step verification turned off and still it foesn't worm for me

**Comment by kingkai808** [comment]
If you have the email saying new sign on from xxxx device click it and confirm it is you.
