### ISSUE TITLE
HashException unauthorized

### ISSUE THREAD

**Issue by Kristantoyussuf** [pokesniperandroid/PokeSniper-Android#210]

**Comment by junaidsur** [comment]
Same here..hash service exception error.. using personal api key. Which i use only..still getting this error

**Comment by JB4815** [comment]
Having the same issue with the hash key error.

**Comment by pokesniperandroid** [comment]
Check release page, hash key updated. Will add more later. Previous keys had been expired.

As your own key, if gets same result, check key expiration.

**Comment by pokesniperandroid** [comment]
Updated keys
https://github.com/pokesniperandroid/PokeSniper-Android/blob/master/KEYS.md

**Comment by vort3xzz** [comment]
I keep getting the same error and when i try to much a temp ban

**Comment by aniket4692** [comment]
i was using this key for last 6-7 days. but today its not working. can you please fix this.

**Comment by pokesniperandroid** [comment]
Yeah, someone keep resetting the keys.
Check keys page for update
https://github.com/pokesniperandroid/PokeSniper-Android/blob/master/KEYS.md

**Comment by aniket4692** [comment]
thank you so much sir. @pokesniperandroid
