### ISSUE TITLE
Pokesniper can't work right now

### ISSUE THREAD

**Issue by sasachan1984** [pokesniperandroid/PokeSniper-Android#211]
Pokesniper now can't work due to HashException unauthorized, Would you mind helping us on this issue? Thanks so much~

**Comment by mylife2805** [comment]
Me too my pokesniper doesnt work anymore since maybe 3 hours i get the same error 
HashException unauthorized.
Anyone know why or can solve the uisses?

**Comment by kabirash** [comment]
Same here. Has the free hash key expired?

**Comment by abhimanyusingh143143** [comment]
I have face same problem in new version beta 13
When hash key is expired plz give us new hadh key to operate to pole sniper

**Comment by pokesniperandroid** [comment]
Check release page, hash key updated. Will add more later.

**Comment by mylife2805** [comment]
No comes the same error 
Im copy the hashkey from here (Beta13) and paste it in the field by hashkey in pokesniper but it gives me the same error why? Is thiss tge right one yes ? 44D8I2L3R2V5T5T5X5L9Y hashkey

**Comment by kkthedoc** [comment]
Even if uninstall, reinstall, fresh LatLong input and Hashkey, still issue persists.

**Comment by pokesniperandroid** [comment]
Yeah, i tested it and it's working fine. And i don't think this is bug on the app. Try with different account, and post the result.

Tested just now with shared key
<img src="http://i.imgur.com/1DfxJl3.png">

**Comment by mylife2805** [comment]
I hope it is right link ^^

[IMG]https://www2.pic-upload.de/img/33043711/IMG_20170421_094915.png[/IMG]

**Comment by mylife2805** [comment]
[img]http://img5.fotos-hochladen.net/uploads/img2017042109wdt8cgsj20.png[/img]

**Comment by mylife2805** [comment]
Why i dont can upload any pic ?

**Comment by kkthedoc** [comment]
Nope, not still working. And my PTC is working absolutely fine. No soft ban
even.

**Comment by mylife2805** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/27829082/25268774/55ce0db8-267a-11e7-95fc-a9f8f735c060.png)

**Comment by mylife2805** [comment]
this is by all my accounts and all are fine no on has a softban etc i can login in normal app.


I am wondering just why it is with you and with others the error comes? Maybe a tip error in the hash key? ^-^

**Comment by mylife2805** [comment]
![ptcacc](https://cloud.githubusercontent.com/assets/27829082/25269349/7cb9b02e-267c-11e7-9b1a-fdd818403d3b.png)
 this one is a new created ptc account for 5 min

**Comment by pokesniperandroid** [comment]
Sorry, seems in the release page, the hash key was typo. Try change to updated one.

**Comment by pokesniperandroid** [comment]
Updated keys
https://github.com/pokesniperandroid/PokeSniper-Android/blob/master/KEYS.md

**Comment by kkthedoc** [comment]
Got it. Up and running. Thanks a plenty, dude. Will try and send a coupla
beers your way! 😊😊☺

**Comment by mylife2805** [comment]
Now it works well 
Ty for your work 
Here a couple of beers for us ^-^
