### ISSUE TITLE
Unauthorized haskey :((

### ISSUE THREAD

**Issue by MisterJohnHanke** [pokesniperandroid/PokeSniper-Android#212]
Whats d prob with this?

**Comment by pokesniperandroid** [comment]
Check release page, hash key updated. Will add more later. Previous keys had been expired.

**Comment by MisterJohnHanke** [comment]
Still not authorized :(

**Comment by Kristantoyussuf** [comment]
Please update new hash key

**Comment by pokesniperandroid** [comment]
Updated keys
https://github.com/pokesniperandroid/PokeSniper-Android/blob/master/KEYS.md
