### ISSUE TITLE
(Pokesniper isn't work) Is there any new Share HashKey for Pokesniper now?

### ISSUE THREAD

**Issue by sasachan1984** [pokesniperandroid/PokeSniper-Android#213]
As title, Hash Exception unauthorized still appears on the screen and we can't log in to the account. Would you mind giving us some others Hash Keys to process the snipping? Thanks so much!

**Comment by pokesniperandroid** [comment]
Updated keys
https://github.com/pokesniperandroid/PokeSniper-Android/blob/master/KEYS.md

**Comment by kabirash** [comment]
That this worked perfectly. Great work😉

**Comment by Kristantoyussuf** [comment]
Not work

**Comment by Kristantoyussuf** [comment]
Its perfectly work. Thanks alot
