### ISSUE TITLE
My question re: donations was not addressed

### ISSUE THREAD

**Issue by heelio357** [pokesniperandroid/PokeSniper-Android#222]
I will ask again - if I donate, will it be possible to obtain a version of this app that does not have the two account limit and (possibly) also no ads? Thank you for response.

**Comment by pokesniperandroid** [comment]
Sorry for unreplied issue. If you donating, you'll get no limit accounts and without ads.

**Comment by andamirorulez** [comment]
How do i donate??

**Comment by heelio357** [comment]
I have donated - how to get the better version?
