### ISSUE TITLE
No catch

### ISSUE THREAD

**Issue by deathgods99** [pokesniperandroid/PokeSniper-Android#24]
the thing just doesnt work, i've got many pokeballs still it just says pokemon fled.

**Comment by pokesniperandroid** [comment]
if it's pokemon fled, check for soft ban in official app

**Comment by snipethemoment** [comment]
Same problem ... no soft ban few hours ago tried to catch some rare pokemon and ... pokemon just fled and pokemon gone... acc fresh no soft ban

**Comment by pokesniperandroid** [comment]
you want to watch this video 
https://www.youtube.com/watch?v=tCN9JHuniBQ

tested the current version without soft ban

**Comment by redv99** [comment]
please update the version bcoz there seem to be a bug that the pokemon fleds even it is the right coords. for those having these problems wait 3 hours for it to work again. but the bug still occurs so pls fix it

**Comment by dxdddd** [comment]
Im not softbanned and it keeps saying it can't catch it i use gmail account

**Comment by pokesniperandroid** [comment]
We don't ever encounter softban except we're setting wrong home coordinates. Try to read [repo's README.md](../blob/master/README.md)
