### ISSUE TITLE
Pls fix!😃

### ISSUE THREAD

**Issue by BinoWassabi** [pokesniperandroid/PokeSniper-Android#25]
Pls fix the latest version the home coordinates is not working i always get soft ban

**Comment by kingkai808** [comment]
Same here

**Comment by BinoWassabi** [comment]
The other new function cant turn on only the razzberries

**Comment by BinoWassabi** [comment]
i like the old position of hunt coordinates 😞

**Comment by pokesniperandroid** [comment]
you want to watch this video 
https://www.youtube.com/watch?v=tCN9JHuniBQ

tested the current version without soft ban

**Comment by BinoWassabi** [comment]
Try google acc sir and the other new function cant enable only the razzberries

**Comment by myhadhy** [comment]
Same here, first i used my 1st account and the home coordinates works, then i used my 2nd account but the pokemons always fled. I tried to unban it manually, then i sniped but the pokemons flee again, i checked it in game turn out i was getting softban again, i already tested it 5 times to be sure. My guess the home coordinates on free version only work for 1 account. Please fix it. :(

**Comment by movement20** [comment]
Same here, keep getting softban / pokemon fled.

**Comment by kingkai808** [comment]
Collision script errors when enabling auto transfer. Turned it off works fine now. 
@pokesniperandroid please make a separate app that's donate only and one that's free. I'm still seeing ads after I upgraded to pro. Not often but randomly they will pop up.

**Comment by pokesniperandroid** [comment]
If you're still seeing ads, please force stop the app and open it again.
