### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DaviidSv** [pokesniperandroid/PokeSniper-Android#26]
- In version 1.2 I did not know what Pokeball used the app to capture pokemon but it worked, not now. I have not softban.

- Fix the problem of transaction ID to donate.

- Mr. Mime still can be captured.

I think it's best to use the v1.2, it is more stable and useful. Thanks anyway for developing this amazing app! I have donated!

**Comment by kingkai808** [comment]
I still have issue with transaction id.

**Comment by kingkai808** [comment]
I have donated and still can't unlock app

**Comment by DaviidSv** [comment]
@kingkai808 The developer has to solve this problem, for the moment still using v1.2

**Comment by pokesniperandroid** [comment]
As for soft ban, we have feedback from 20 test users, and they didn't encounter any soft ban in their account. But, we'll look into it. And for transaction ID, our donate system automatically capture any transaction ID from completed donation. But, if your transaction ID didn't work, please send email to donate@pokesniperandroid.com (as stated in success page). Sorry for the inconvenience and thank you. And the last for Mr.Mime, the fix has been applied in current version. Still, we'll look into it too.

**Comment by pokesniperandroid** [comment]
you want to watch this video 
https://www.youtube.com/watch?v=tCN9JHuniBQ

tested the current version without soft ban

**Comment by DaviidSv** [comment]
I have already captured with this version, but I find the most effective system for pokeball wearing v1.2... In the other system did not use berries and used standard pokeball but Lapras and Snorlax never flet, now it is. If you can implement the old system, it would be great :)

For Mr. Mime, I have seen in other bots (computer) that the error was by name, maybe that is the case.

Thanks!

**Comment by pokesniperandroid** [comment]
Maybe we will implement two method, one is with old method (automatically) and two is with new method (pick what pokeball to use), so users will choose one of those method to use.
