### ISSUE TITLE
Another Good Suggestion.

### ISSUE THREAD

**Issue by parind** [pokesniperandroid/PokeSniper-Android#27]
We saw you introduced new things in the new update. And the donate function too. But as you are generating money from StartApp's and Google's ads, it would be good if you can give an option to Enable the pro features for free but keeping the ads enabled. As a result the indirectly earn money & we get to use the features.

**Comment by pokesniperandroid** [comment]
We think it's a good idea. We just divide the pro features such as auto transfer, multiple accounts without limit because feedback from some users says that some features need to be limited for free users. Then, we'll do it in the next update. Thank you.

**Comment by parind** [comment]
Okay will wait for your next update to get this. Thank you for replying.

**Comment by parind** [comment]
Hey even in the latest update. There's an issue with Home Cordinates. They might be getting an error. So it soft bans the account.

**Comment by snipethemoment** [comment]
Yep my second big account lvl 29 got soft ban after first hunt with this app . Idk where to find the home account ... that's fkt up anyways great app

**Comment by pokesniperandroid** [comment]
you want to watch this video 
https://www.youtube.com/watch?v=tCN9JHuniBQ

tested the current version without soft ban

**Comment by snipethemoment** [comment]
What about home coordinates? How to find them cuz that's the reason that i got softbanned.

**Comment by pokesniperandroid** [comment]
Home Coordinates: This coordinates are the last coordinates you play. If you were playing with bot, use the last coordinates on that bot. If not, the last coordinates you login into Pokemon GO.

**Comment by kingkai808** [comment]
I donated earlier and I still didn't get my transaction I'd to register. Keeps saying invalid. Please help @pokesniperandroid

**Comment by pokesniperandroid** [comment]
@kingkai808 if your transaction ID didn't work, please send email to donate@pokesniperandroid.com (as stated in success page). Sorry for the inconvenience

**Comment by kingkai808** [comment]
Ok I've sent an email already. Thanks
