### ISSUE TITLE
Beta 23 cannot detect Pokemon

### ISSUE THREAD

**Issue by ebkeong** [pokesniperandroid/PokeSniper-Android#270]
This new version cannot detect Pokemon even when the coordinates are correct. I verified this by driving to the coordinates to catch the Pokemon. Please help.

**Comment by sigitnugroho181211** [comment]
Me too. I guess sniper get banned by Niantic. It stopped working after I snipe few days ago.

**Comment by ebkeong** [comment]
Oh. It's version 0.79.2 now. Eagerly awaiting beta 24

**Comment by sigitnugroho181211** [comment]
:heart_eyes: me tooo
