### ISSUE TITLE
Cant catch Mr.Mime, pls fix!

### ISSUE THREAD

**Issue by movement20** [pokesniperandroid/PokeSniper-Android#36]
It keep shows up "no more mrmime to catch", please help!!

**Comment by Magamar01** [comment]
Is it saying that mr.mime fled or that there was no mr.mime to begin with? Try downgrading to 1.2. 1.3 wasn't working for me but 1.2 works.

**Comment by pokesniperandroid** [comment]
Please update to latest version.
