### ISSUE TITLE
FORCE CLOSE ON KITKAT

### ISSUE THREAD

**Issue by Omanez** [pokesniperandroid/PokeSniper-Android#4]
Fix it soon please..

**Comment by divakar123** [comment]
Yea same issue 😥

**Comment by byungaw031** [comment]
Same😥😥

**Comment by roofyoreppin** [comment]
Same here waiting for a fix

**Comment by pokesniperandroid** [comment]
please update to latest version, if force close still appear, don't hesitate to report
