### ISSUE TITLE
Constantly Soft Banned

### ISSUE THREAD

**Issue by VegetaIsKing** [pokesniperandroid/PokeSniper-Android#41]
I always set my home coordinates perfectly, and make sure that it was the last coordinates that I was logged in at, but no matter what I do the pokemon will flee and I'll be given a soft ban.

I dont know what I'm doing wrong at all and want to know if anyone else is having the same issue, I'm using 1.3, I tried using 1.2 but that didn't even work for me.

It worked once for a little while, but then it stopped and I got soft banned, help, please?

**Comment by toade** [comment]
I have the same problem now

**Comment by kingkai808** [comment]
Stop using 1.3 until 1.4 comes out. Use 1.2 for now.
