### ISSUE TITLE
READ THIS FIRST BEFORE POSTING A NEW ISSUE.

### ISSUE THREAD

**Issue by parind** [pokesniperandroid/PokeSniper-Android#45]
In the new version 1.3. There were many changes & new additions bought to the App. So there were a couple of Bugs like the "Home Co-ordinates" bug which the developer already knows. So dont even hesitate to post this issue again & again, thus disturbing the Developer on his work.
I am not any member of this team.

**Comment by parind** [comment]
#2. The developer is also aware of the MrMime bug.

**Comment by kingkai808** [comment]
And hopefully aware of the unknown exception error when using raspberries and auto transferring pokemon after catching.

**Comment by cire27rn** [comment]
We will not post again if anyone posted, "new version on the work"

**Comment by parind** [comment]
@cire27rn Thats not going to help the dev.

**Comment by parind** [comment]
No Issue's found in the latest version. Thank you dev for this Stable Release
