### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by dalord3532** [pokesniperandroid/PokeSniper-Android#46]
I dont know what I'm doing wrong
But I'm getting failed to login error.
Not able to use this apk
Please help

**Comment by ethan061903** [comment]
ive had this problem try using no capital letters in your username and password

**Comment by dalord3532** [comment]
I am using in small only. Still the same

**Comment by pokesniperandroid** [comment]
Please update to latest version. If the credentials are correct, you should logged successfully. If not, try with another account.
