### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by dxdddd** [pokesniperandroid/PokeSniper-Android#47]
Every Pokemon i try to catch flees your app has not worked for me one time

**Comment by fackieollie** [comment]
@dxdddd yes i think there was a bug on putting coordinates on account. i did other format but failed.

1st i log in my ptc account that i never used like 24 hours. the program works flawless.
2nd i used my other google account. yes i used in bot. when i login and input the details. all pokemon fled. i did manual unsoftbanned and tried the manual snipe. i got caught but when i switch to pokesniper android. with the same coordinates . pokemon fled again.. thats i think theres a bug on putting coordinates thats why we get softbanned instantly

**Comment by MrCrunchy** [comment]
Are you remembering to actually set your location in app? You have to set your home coordinates gps style (xxxxxx, xxxxx) in order to avoid the soft ban. Otherwise when soft banned they will all flee.

**Comment by fackieollie** [comment]
Yup the developer already knows the bug in home coordinates we should just wait to fix it.

**Comment by dxdddd** [comment]
Yea i have my home coordinates im not a dumass fucking asshole

**Comment by MrCrunchy** [comment]
You are sensitive like a little bitch though ;)

**Comment by dxdddd** [comment]
Dude you can't talk about being bitch cause I'll fucking break your skull and leave you entrails splattered all over your mom's FUCKING wall

**Comment by dxdddd** [comment]
😇😇😏😆

**Comment by dxdddd** [comment]
😇😇😏😆

**Comment by MrCrunchy** [comment]
Lol lol lol lol lol you obviously don't have your home coordinates I don't get banned lol lol lol lol

**Comment by MrCrunchy** [comment]
Must be a "dumass" dumb ass 😇😇😏😆

**Comment by dxdddd** [comment]
SHUT UP FUCKING PIECE OF SHIT I GONNA HANG YOU UP LIKE A FUCKING PIG AND MAKE YOU CUT OUT YOUR OWN HEART

**Comment by dxdddd** [comment]
And i do have my home coordinates

**Comment by dxdddd** [comment]
😎🖕🖕🖕😈

**Comment by MrCrunchy** [comment]
Lol lol lol how does one cut out their own heart? At least make the threats believable..."dumass"

**Comment by MrCrunchy** [comment]
If you had them in right you wouldn't be banned  😂😂😂😂😂😂😂😂😂

**Comment by dxdddd** [comment]
One cuts out their own heart cause  the adrenaline rush you get let's you finish the job dumass fucking PIECE of shit damm fucking keyboard warrior probably still live in your moms basement eating chicken nuggets and watching spongebob

**Comment by MrCrunchy** [comment]
Lol adrenaline rush? You need to inject adrenaline you mean.  Hahaha hahaha so ignorant haha no wonder you get banned and don't know how to set home coordinates 😂😂😂😂😂😂😂

**Comment by MrCrunchy** [comment]
Ooh caught Mr Mime :)
