### ISSUE TITLE
v1.4 adblock error

### ISSUE THREAD

**Issue by gdarya** [pokesniperandroid/PokeSniper-Android#48]
I didn't use any adblock but the app suggest to disable adblock first in order to use the app. Is that a bug?

**Comment by MrCrunchy** [comment]
I have the same issue. I'm guessing this is a bug?

**Comment by ethan061903** [comment]
same here i have reinstalled v 1.3 amd it works fine and ive done everything like deleting all data but i want to use 1.4 because theres a anti softban thing and i want it sobaaaad

**Comment by ethan061903** [comment]
also i want mr.mime

**Comment by MrCrunchy** [comment]
I just want mr mime as well :D

**Comment by pokesniperandroid** [comment]
Hello,

Please use previouse version, there's something wrong when compiling the apk. Still look into it. Sorry.

Thanks

**Comment by ethan061903** [comment]
Thank You So Much!!!

**Comment by MrCrunchy** [comment]
Thanks for your hard work.

**Comment by pilman** [comment]
I used version 1.3 but no more pokemon to catch

Im trying version 1.4 adblock error

**Comment by pokesniperandroid** [comment]
Hello,

Version 1.4 should be fixed, please re-download the file.  If problem still persist, don't hesitate to report.

Thanks.

**Comment by wandymz3** [comment]
Version 1.4 still getting disable adblock
