### ISSUE TITLE
Not Catching Pokemon

### ISSUE THREAD

**Issue by paulination** [pokesniperandroid/PokeSniper-Android#5]
Does this still work because of the soft ban issues? I put coordinates of home/place I play most. Been trying to catch, but always failed or pokemon gone, what does that mean? Is that softban? Thank you...

**Comment by parind** [comment]
Have you tried logging in your account through the game. If it gives you an error "Failed to get data from server" or "thank you for your humble response..." you are Hard Banned. If it logins & Pokestops do spin but you dont receive any Items then you are Soft Banned.

**Comment by paulination** [comment]
Oh, I'm talking about the sniper app. My account is working fine. But the app is not letting me snipe anything. Always pokemon gone or something.

**Comment by parind** [comment]
Update to the latest version. Released now. Working fine in my dummy account.

**Comment by paulination** [comment]
Okay. It works now. Thanks.

**Comment by revephraim** [comment]
I'm having an issue with sniping. It's always saying Pokemon  gone. Checked to see if I was soft banned in the official app, but I can catch Pokemon there.

**Comment by neospeed83** [comment]
@parind hi my main account says failed to get game data from server after using this app. Am i permanently banned ?

**Comment by kingkai808** [comment]
Yes. Yes you are.
