### ISSUE TITLE
Donated but app does not accept transaction ID

### ISSUE THREAD

**Issue by clarkdevlin** [pokesniperandroid/PokeSniper-Android#51]
Donated via paypal to remove adds and for extra features but when I entered the transaction ID that I received from paypal's email the app says invalid transaction ID. I donated 2 more times to try it out but still failed. So how?

**Comment by toade** [comment]
I did the same thing and got the same msg invlid id

**Comment by clarkdevlin** [comment]
So i tried again just now and now it is just stuck at CHECKING.... but nothing is happening for over 10 mins already.

**Comment by pokesniperandroid** [comment]
Hellom

Please update to latest version, and use your paypal email in donate menu. If it's still giving no response, means our server still giving error response. For some users, it succeed. Will update you again. Sorry for the inconvenience.

Thanks

**Comment by pokesniperandroid** [comment]
Hello

Server has come back online, you may try again.

Thanks.
