### ISSUE TITLE
Unknown Exception 

### ISSUE THREAD

**Issue by MrTurtle500** [pokesniperandroid/PokeSniper-Android#52]
So I have the 1.3 version, and it is a system app using lucky patcher.   I select a pokemon from Rarespawns.be and click snipe. Then it runs to the point of selecting poke all then gives Unknown Exception, and the pokemon is not caught. I've tried pokezz.com and still same issue,  I've even Uninstaller and reinstalled the app.

**Comment by pokesniperandroid** [comment]
Hello,

Please update to latest version. If problem still persist, don't hesitate to report.

Thanks.

**Comment by MrTurtle500** [comment]
Hasn't happened since I've updated to version 1.4,  thanks!
