### ISSUE TITLE
Pokebag

### ISSUE THREAD

**Issue by adventemikl** [pokesniperandroid/PokeSniper-Android#55]
Since the release of pokebag, all pokemons caught though appeared in pokebag but it's not in pokemongo itself

**Comment by pokesniperandroid** [comment]
Hello,

For latest release (1.4), all features has been tested. Known issues: always using razzberry. Except that, maybe soft ban for some people (we don't know how it could happen, our testers says it's fine and no soft ban). Try with another or fresh account.

Thanks
