### ISSUE TITLE
Donators need separate app.

### ISSUE THREAD

**Issue by kingkai808** [pokesniperandroid/PokeSniper-Android#56]
Verify donation I'd not working again. Just keeps relooping and crashing after hitting submit. 
Also using pokebag causes crash when adding new account and then immediately checking pokebag using new account or when switching between accounts.

**Comment by pokesniperandroid** [comment]
Hello,

If you use latest version (1.4), there shouldn't be a problem.

Thank you.

**Comment by kingkai808** [comment]
@pokesniperandroid it keeps saying checking and does nothing. Once I click submit it says checking and goes back to submit.

**Comment by pokesniperandroid** [comment]
Hello,

Please send me an email to donate@pokesniperandroid.com with your paypal email address/

Thanks.
