### ISSUE TITLE
Pokemon Fled Versions 1.3 and 1.4

### ISSUE THREAD

**Issue by shawnd443** [pokesniperandroid/PokeSniper-Android#57]
Hi I am also having the same issue of Pokémon fleeing in both versions 1.3 and 1.4. Everytime I snipe a Pokemon, I receive a "Pokemon has fled" message immediately which then results in an immediate soft ban. I set my home coordinates to the place I play most which is my home address. Please address and fix this issue ASAP!!

Thanks

**Comment by pokesniperandroid** [comment]
Hello,

Please watch this video, https://www.youtube.com/watch?v=tCN9JHuniBQ
As we have stated in Readme, coordinates is very crucial. We were setting up correctly and we got no softban (not even once) except when we set up wrong coordinates. And this were already tested by our inner testers (no softban too).

Thanks.

**Comment by insider111** [comment]
your account softband , wait 6 hours and open pokesniper
