### ISSUE TITLE
Stuck in attempt to catch pokemon

### ISSUE THREAD

**Issue by zoryox** [pokesniperandroid/PokeSniper-Android#58]
As the title says the app works fine until it starts ti catch the pokemon and stays like that forever.

Fix please?

Also tried 3 different devices with 3 different accounts.

**Comment by cire27rn** [comment]
Maybe you're having a slow internet or got disconnected then returned

**Comment by zoryox** [comment]
My bad,i found that my latitude was + while it should of been -

It works perfectly now,i caught a shit ton of pokemons!!thx
