### ISSUE TITLE
Can't catch anything 

### ISSUE THREAD

**Issue by BrownSurprise9** [pokesniperandroid/PokeSniper-Android#60]
Everytime I try to snipe, I keep getting "no more (Pokemon name) to catch". It's not like I ran out of time and the Pokemon despawned, there's at least 5+ minutes left.

**Comment by cire27rn** [comment]
What version did u use? Are u sure u have poke balls left? Have u reached the max pokemon to 250? Is mr mime u were capturing from the old versions?

**Comment by BrownSurprise9** [comment]
Ok so I transferred a few pokémon and that did the trick, thanks for your help.
