### ISSUE TITLE
Having trouble with home corridinates can anybody help

### ISSUE THREAD

**Issue by getmoney808** [pokesniperandroid/PokeSniper-Android#62]

**Comment by shawnd443** [comment]
I had the same issue yesterday. The fix I found was to not put a space between each of the coordinates.

EX1 42.6745, -23.4568 (HAS A SPACE DO NOT DO)
EX2 42.6745,-23.4568 (HAS NO SPACES DO THIS)

Of course use your own home coordinates. Hope that Helped

**Comment by getmoney808** [comment]
Thanks it was the using the cords from where i signed in last

**Comment by shawnd443** [comment]
Did that work for you?
