### ISSUE TITLE
No more issues with the latest v1.4.1

### ISSUE THREAD

**Issue by cire27rn** [pokesniperandroid/PokeSniper-Android#64]
Mr mime working
No soft ban issue
No more using of razzberries always
Auto transfer option is working

Thank you! 😉

"Lets snipe those bitches"

**Comment by Antlersimon** [comment]
Why pokemon fled ?

**Comment by cire27rn** [comment]
Sometimes a pokemon fled does not mean ur soft ban. But if its 3x straight, that would do.
