### ISSUE TITLE
pop up ads

### ISSUE THREAD

**Issue by namekwarrior** [pokesniperandroid/PokeSniper-Android#68]
Good day Sir. Can you please remove the pop up ads while in the process of catching pokemon? Because sometimes the app will just freeze and will not catch the pokemon. Or maybe you can just put the ads after catching the pokemon. I hope this can be done in the coming updates. Thank you.

**Comment by zidonlime** [comment]
Donate

**Comment by cire27rn** [comment]
+1

**Comment by zacho96** [comment]
I donated I still have adds
