### ISSUE TITLE
Sniping vs botting?

### ISSUE THREAD

**Issue by Freshink808** [pokesniperandroid/PokeSniper-Android#69]
Is this app safer then the gosimulator app?

**Comment by kingkai808** [comment]
Go Sim is purchase only. And sniping is safe. Until patched or api changes.

**Comment by Freshink808** [comment]
I still have the latst version of gosim. Which has least chance of ban?

**Comment by kingkai808** [comment]
Sniper.

**Comment by ILJJAYDK** [comment]
I think none is safe cause I got already ban in my 2 of account.. but still using both of this application. Use it wisely and you will not get banned. I used to snipe 5-6 Pokemon a day and 6 to 7 hrs of boting a day in this new account.It is now 4 days and still not ban .Idk about future will let u know if something happens

**Comment by Freshink808** [comment]
Thanks

**Comment by cire27rn** [comment]
Im also using the updated go simulator to my 2nd acct and still i havent got banned and i think its harder to detect because it was carefully planned especially the steps. I use the pokesniper to my acct because i know it is safe especially there's the home coords.

**Comment by ILJJAYDK** [comment]
Still working my both Sniping and bo account

**Comment by zeroandten** [comment]
can i have a link were i can download the latest pokemon go simulator

**Comment by kingkai808** [comment]
no link for go sim anymore. dev closed it. if you want it its $15. just download go manager from git hub. better bot and easier to use.

**Comment by parind** [comment]
@kingkai808 Can you post the Go Manager link. I cant find it or just write the Dev's Repo.
