### ISSUE TITLE
Pokemon fled keep coming this message is that get banned ?

### ISSUE THREAD

**Issue by Jeremyzzz** [pokesniperandroid/PokeSniper-Android#70]
Hi everyone would like to ask im using pokesniper to catch those pokemon but the result keep saying pokemon fled ? Is that my account in watch list ?

**Comment by MrCrunchy** [comment]
Yes typically means 24 hrs ban

**Comment by Jeremyzzz** [comment]
Any way can solve that ?

**Comment by MrCrunchy** [comment]
Wait is all you can do.  Make sure your home coordinates are put in right.  I also use fake gps Android app. I copy the gps coordinates from pokesniper and fake my location as the same location of the Pokemon I'm catching.
