### ISSUE TITLE
No more "Pokemon" to catch.

### ISSUE THREAD

**Issue by Negrataish** [pokesniperandroid/PokeSniper-Android#71]
It doesnt say that they fled, just that there is no pokemon everytime i try. It worked a few days ago, but since then i cant snipe anymore.
Its a softban?
I can login in the official app btw but didnt try to catch something

**Comment by zkenstein** [comment]
pokemon storage full?

**Comment by kingkai808** [comment]
you're ip banned. try logging into the real game. if it says failed to authenticate then change your ip address.

**Comment by zidonlime** [comment]
Pokemon storage full

**Comment by kingkai808** [comment]
Transfer some pokemon out and try again.
