### ISSUE TITLE
Ads destroy the apps

### ISSUE THREAD

**Issue by tengkuaizat** [pokesniperandroid/PokeSniper-Android#72]
Almost everytime when we tried to snipe, the ads video pop ups and the status of pokesnipe will stuck. We need to press the snipe button again, and the same thing happen. You really need to control on how your ads will appear in PokeSnipe as the apps is almost unusable on slower device (low on ram) such as Xiaomi MI3.

I am aware that we can donate to remove the ads, but that is not the case. I can deal with ads within the apps as long as the ads doesn't destroy the ability of the apps itself.

**Comment by ILJJAYDK** [comment]
Bro it's a free software..We should support app developer

**Comment by tengkuaizat** [comment]
yes I am aware that it is a free software and I do support the dev by giving honest feedback.  The issue right now is the apps is hard to working properly in slower/low on ram devices which render this apps useless. What I am asking right now is just fix the way that ads appear in the apps so the ads doesn't interfere in the middle of sniping for example. I am not asking them to remove the ads totally.

**Comment by kingkai808** [comment]
what i recommend the dev do i set video ads at 5 min intervals and show all regular ads/video ads AFTER pokemon have been caught/flee rather than pop up after successful login, then again i donated to the dev, so i dont know about this ad problem you speak of. /flex

**Comment by zidonlime** [comment]
Stop complaining about ads. There are option to remove ads... DONATE.

**Comment by tengkuaizat** [comment]
@zidonlime Yes I am aware of that option to remove the ads. What is the point of the 'free' version of the apps if it didn't work because of the ads? I can donate, and as I stated before that is not the case.

All I do is stating a bug in a 'non-donate' version of Pokesnipe that render this apps useless in slower device when the ads pop-up in the middle of sniping. Not complaining about the ads. Please, read.

**Comment by zidonlime** [comment]
Click X or no thanks. I don't see any problem.

**Comment by kingkai808** [comment]
the video ads disrupt the feed thats why. doesn't show whether you caught it or not. can be frustrating thats why i donated. dev should put the ads so they pop up after a catch.

**Comment by clarkdevlin** [comment]
using 1.4.1 donated and ads were gone, but now ads are back.

**Comment by zidonlime** [comment]
I did not had ads issue after donate.
