### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by kiketsu** [pokesniperandroid/PokeSniper-Android#73]
im using the last version 1.4.1 and whrn i try to catch a pokemon it keeps saying "pls disable adblock and i dont have any adblock installed

**Comment by BeeTLeApp** [comment]
Open rootexplorer. Enter system/etc directory. "hosts" folder is rename example hosts1

**Comment by mokenneth** [comment]
no 'hosts' directory under system/etc.  please help

**Comment by BeeTLeApp** [comment]
is your phone root? Try searching /system . if not found,try creating your own hosts file.Maybe work

**Comment by mokenneth** [comment]
my phone is rooted.  no 'hosts' directory under etc

only have a file named 'hosts'?  should i rename the file to 'hosts1'?
![screenshot_2016-09-10-18-21-39](https://cloud.githubusercontent.com/assets/22109429/18409837/ebbf376c-7783-11e6-8ce9-e18c9c555130.png)

**Comment by BeeTLeApp** [comment]
Yes,trying rename hosts1 and open pokesniper.

**Comment by mokenneth** [comment]
thanks

**Comment by LeoRedin** [comment]
So I have no root on phone. But the custom rom I have came with and ad block. I disabled it, restarted phone but I can't use the pokesniper. Any suggestions?
