### ISSUE TITLE
Device id question

### ISSUE THREAD

**Issue by Freshink808** [pokesniperandroid/PokeSniper-Android#74]
Does this app change your device id and is it a shared id everyone ends up using when app is used? Also does this app use a local server near you when sniping? Thanks

**Comment by parind** [comment]
Ya. @pokesniperandroid Does this app use the device's Device ID or it uses a Same device id for everyone. If it seems so that it uses Same Device ID it could get us all (Pokesniper Users) banned in the following weeks.

**Comment by kingkai808** [comment]
i hope it doesn't. if it is dev just banned us all. lol
he should have built in a randomizer device id. all the current bots have it.  would be easier to set device id settings rather than being hidden. maybe next update? show device id and include a randomizer id option for people who donate. @pokesniperandroid

**Comment by parind** [comment]
Oh yes @kingkai808 @pokesniperandroid. Else it would be awesome if we could set our own Device ID. Just so as we know "Precaution is better than Cure"

**Comment by kingkai808** [comment]
i have a randomize device id on my bot so i can "create" unlimited fake device id's that i want, but i hope dev, adds this feature into 1.5. and remove the your account may be banned error cuz its freaking people out lol and replace it with "the connection to the server was interrupted, please check poke bag to see if pokemon was caught already, if not try again"

**Comment by pokesniperandroid** [comment]
Hello,

It's using your current device information. So, every devices has unique info. We still working on new feature, and may be late when responding to bugs and such.

Thanks.

**Comment by kingkai808** [comment]
youre doing great man! have you read my thread about the catch em bot? would be cool if you could port his bot to android form. would definitely donate for that. @pokesniperandroid

**Comment by parind** [comment]
@kingkai808 Really that error nearly freaks me everytime too. 
And @pokesniperandroid Good to hear that the Device ID uses our own Device ID. Really thats a good thing to hear. Tysm Dev.

**Comment by Freshink808** [comment]
Well its good that it uses our device id rather us all sharing the same ones. So im assuming its using our phone ip as we'll?

**Comment by parind** [comment]
Might be becoz the Request it may be sending through the Protobuf is working on own device And therefore must be sending thru our own IP add

**Comment by kingkai808** [comment]
Use a VPN if you're worried about your IP.
Lots out there. But lots of ups are banned already. I use a paid one. So my IP isy IP and no one else uses it. I NEVER log into anything with my real IP ever. Get a VPN guys. Hide your ass. Touch VPN still has some unbanned IPS for pokego.

**Comment by Freshink808** [comment]
Whats the vpn app you use? Also whats the plus side of always changing your ip, dont you think that maybe always having a diffrent ip on an account might raise a niantic flag? Just wodering guys, thanks @kingkai808

**Comment by kingkai808** [comment]
I use ipvanish.
No it doesn't. Its like if you went to Starbucks and used their WiFi. Is that a flag? Or mcds or walk mart WiFi? If they banned people based on frequent IP changes then millions of people (legit) will be gone. They only ban the IP of known fake IP services like vpns. But at least your real IP isn't banned. Just get another one :)

**Comment by Freshink808** [comment]
Shyt i didnt think of that lol 
Does that app have a recurring charge every month?
@kingkai808

**Comment by kingkai808** [comment]
I pay 8.99 a month. 
I sell poke accounts that are guaranteed not get banned ever. Let's just say I don't have to worry about the monthly charge. :)

**Comment by Freshink808** [comment]
Nice! You think i would need to change my ip to use go sim where i live? @kingkai808

**Comment by kingkai808** [comment]
the answer is always cuz if u get hacked they have a harder time tracing u

**Comment by kingkai808** [comment]
Where u at? Oahu?

**Comment by Freshink808** [comment]
Big island
