### ISSUE TITLE
No more Dragonite Catch

### ISSUE THREAD

**Issue by BeeTLeApp** [pokesniperandroid/PokeSniper-Android#75]
Dragonite,charizard,Blastoise,Hitmonlee,Hitmonchan is not catch . Coordinates true . Pokesniper is see pokemon but not catch.Other pokemons no problem.Could you help?

**Comment by kingkai808** [comment]
Its not there really that's why. Make sure its a verified position first.

**Comment by BeeTLeApp** [comment]
To dozens coordinates try. Only this pokemons some problem. I hope you understand my english not good

**Comment by kingkai808** [comment]
i have encountered this before but i make sure i only catch ones that are verified on pokezz.com

**Comment by BeeTLeApp** [comment]
I use pokezz.com i said to dozens coordinates try. i dont understand why.I tought application error or bug.

**Comment by kingkai808** [comment]
never ran into your bug before?

**Comment by BeeTLeApp** [comment]
i didn't want to write long. My pokedex see 118 pokemon.Other 27 pokemon not catch. Example a few coordinates for pikachu.Tap the snipe button.Pokemon sight:1 no more pikachu to catch or primeape pokemon i m trying again but some again write.

**Comment by gdarya** [comment]
Your pokebag is full. Try to delete some

**Comment by BeeTLeApp** [comment]
No full bag.Same times play pokemon go orginal app.I make control my bag.

**Comment by BadSly** [comment]
what are the other sites that have verified pokemon other than pokezz.com?

**Comment by BeeTLeApp** [comment]
i have tried many. Uncaught pokemons, using bot go simulator or pokebot caught.Only pokesniper not catch. i dont think that the coords.Another things but i dont understand
