### ISSUE TITLE
"Your Account Might Got Banned" problem still exists 

### ISSUE THREAD

**Issue by JrMalhar** [pokesniperandroid/PokeSniper-Android#76]
Hello all. Plz help. 
I have logged in with my PTC account. But it says "Your Account Might Got Banned". I caught a pokemon with the official app and within minutes I tried pokesniper and it says the same thing. It works fine with Gmail account but why not with my PTC? Where have I gone wrong? I'm not even soft banned. I tried both versions 1.4.1 & 1.4. My ptc account has 50great balls and 25 ultra balls but 0 normal pokeballs. Is it because of this? I'm using correct pokemon Co ordinates and also correct home Co ordinates. Plz help

**Comment by kingkai808** [comment]
Set it to use ultraball or great ball.

**Comment by JrMalhar** [comment]
@kingkai808 Where can I make such setting?  All I can see is 1.use razzberry 2.auto transfer 3.min cp 4.min iv  and 5.prioritize iv over cp.

**Comment by JrMalhar** [comment]
@kingkai808 SITUATION UPDATE 
I now have 100 normal pokeballs. Still facing the same issue. Why? I'm able to catch pokemons with official pokemon go app.

**Comment by cire27rn** [comment]
Maybe you're having internet connection problems probably a slow connection or fluctuating. I have also encountered that but i kept on clicking snipe those bitches until login success

**Comment by kingkai808** [comment]
Internet is bad and it will have the error with disconnect. If you're using VPN try to use one with best ms ping <30 ms
