### ISSUE TITLE
the v1.3-1.4.1 no worked for me

### ISSUE THREAD

**Issue by roe-en** [pokesniperandroid/PokeSniper-Android#79]
I preffered using v1.2 less ads so the ads doesnt make pokemon gone, i think the ads made the connection drop so many times causing the connection to server is interupted.. I can snipe more pokemon using v1.2 rather than v1.3, 1.4, 1.4.1 
![screenshot_2016-09-05-11-40-31](https://cloud.githubusercontent.com/assets/21009046/18237589/a60cf2a6-735d-11e6-94ac-fe3117cb85c5.png)

**Comment by kingkai808** [comment]
Your account is banned. :)

**Comment by pokesniperandroid** [comment]
Hello,

Sorry for the late response. If there's pokemon(s), but you couldn't catch it, sometimes it could meant your account is banned, or couldn't encounter with pokemon, or there's no pokemon you want to catch. 

Thanks
