### ISSUE TITLE
Not catching any Pokemon (not softbanned)

### ISSUE THREAD

**Issue by revephraim** [pokesniperandroid/PokeSniper-Android#8]
Note: Posted this in another thread sorry. Meant to submit as new issue.

I'm having an issue with sniping. It's always saying Pokemon gone. Checked to see if I was soft banned in the official app, but I can catch Pokemon there.

**Comment by skidiiot** [comment]
Do you have Pokeballs?

**Comment by revephraim** [comment]
Yes, I log into the official app and I can catch Pokemon there as well as the Pokemon Go Simulator.

**Comment by AnimeCS** [comment]
Me too have this problem,always the app say the pokemon is gone how we can fix?

**Comment by powerboxizm** [comment]
Use version 1.1 same problem here downgrading fixed it

**Comment by revephraim** [comment]
I tried that method too but no luck
