### ISSUE TITLE
donated,verified but ads still show.

### ISSUE THREAD

**Issue by sawadeegit** [pokesniperandroid/PokeSniper-Android#81]
hi.
I used 1.4.1 and donated,verified in app but sometime ads still show.
Thanks you.

**Comment by Kinderjw** [comment]
Same with me.  Even after verified

**Comment by pokesniperandroid** [comment]
Hello,

Sorry for the late response. Try to force stop the app then re-open the app again. Sometimes, cached ads is still showing.

Thanks

**Comment by sawadeegit** [comment]
I try  but not work,ads still show
