### ISSUE TITLE
Emails other domains

### ISSUE THREAD

**Issue by kerjboy** [pokesniperandroid/PokeSniper-Android#88]
Why do i can't use other email domains like what i used in my Pokemon go acct? Like Icloud.com and newlhs.com???

**Comment by kingkai808** [comment]
please stop using this app. this is the most retarded question that's been asked,

**Comment by MrCrunchy** [comment]
doesn't have to be Google. just put your username and password and don't slide the bar saying "Google account?"

**Comment by kerjboy** [comment]
@MrCrunchy i know how it works. I have three dummy accts in google and it works fine. But i want to use the app in my main acct in PoGo but i use icloud email on it. I hope the next next update of this app will support other email domains.
