### ISSUE TITLE
Highly reccommend

### ISSUE THREAD

**Issue by kingkai808** [pokesniperandroid/PokeSniper-Android#89]
you stop using this  api version as niantic will ban you soon. the dev needs to rewrite a new api so its codestring aren't detected by niantic. i used this on a handmade account i tested on only and it's been banned, just a warning. wait till next update.

**Comment by kerjboy** [comment]
Fuck off!!!!

**Comment by kingkai808** [comment]
Hey ur funeral. Idc

**Comment by kerjboy** [comment]
No one will believe on your BULLSHIT!!!! So STFU!

**Comment by zidonlime** [comment]
Go away

**Comment by kingkai808** [comment]
Kerjoys butthurt because he asked a stupid question 😂😂😂😂

**Comment by kingkai808** [comment]
Like zidon said go away.

**Comment by MrCrunchy** [comment]
been using without problems. are you ghosting your GPS prior to trying to catch? or simply running the app on its own?

**Comment by kingkai808** [comment]
Just using the app on its own. Haven't had a problem before. But suddenly my reg acct got banned. So I made a fake one to test it and I only sniped on that account it just got banned

**Comment by MrCrunchy** [comment]
I always use "fake gps" prior to hitting "snipe those..." haven't been banned yet. caught 50 pidgey this morning. I know entering home coordinate are supposed to prevent bans but I got banned on a prior version despite that so started using fake gps. something you might try once ban clears?

**Comment by kingkai808** [comment]
Its a perma ban failed to get data ban.
I'll try it on another fake account. See if it works thanks man!

**Comment by MrCrunchy** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/requests/new?ticket_form_id=233187 try appealing the ban. I had a friend say he didn't realize the app he used was against the tos etc and apologize and he got the ban reversed.

**Comment by kerjboy** [comment]
I'm not butthurt to anything. I'm using this app for weeks in my three accts without problem and i didn't get banned by using it. In your situation you're just an IDIOT.!

**Comment by zidonlime** [comment]
Same.  No issue atm

**Comment by Jacknator** [comment]
No ban problem lol
