### ISSUE TITLE
New updated api for pogo?

### ISSUE THREAD

**Issue by kingkai808** [pokesniperandroid/PokeSniper-Android#92]
Niantic will force update soon and that means any api's using the old api will not work and flag your account for banned if api calls are made from it. I wouldn't use this until new updated api is out. As it is changed a lot.

**Comment by pokesniperandroid** [comment]
If the new api is released, then we will work on it asap. For now, we should be careful when playing with PokeSniper.

**Comment by kingkai808** [comment]
There is a beta out on pogodev

**Comment by stratosfear7** [comment]
So should we use this program or not?
