### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by mokenneth** [pokesniperandroid/PokeSniper-Android#96]
i installed the last update ver. (v1.5.0) installed successfully but it failed to run (force close).  (already uninstalled the prev. ver.)  please advise

thanks

**Comment by KHARUROSU** [comment]
Same here, uninstalled previuos version and 1.5.0 force close every time i open it.

**Comment by pokesniperandroid** [comment]
We didn't face any force close so far on different android version: Kitkat, Lollipop, Marshmallow and Nougat. Try to force stop the app, then clear data and try reopen again.

If you don't mind, please tell us your device type and OS version.

**Comment by KHARUROSU** [comment]
Hello, on v1.5.1 same beahaviour, force close automatically when i try to start the app.
My device is Samsung Galaxy Alpha, Lollipop. I already cleared cache, unistalled app and installed again, rebooted the phone but the app always force close.

Keep up with the good work.

**Comment by mokenneth** [comment]
my device is samsung galaxy note 3, os 5.0, non-rooted

**Comment by KHARUROSU** [comment]
It only happens on my Galaxy Alpha. It works perfectly fine on my tablet and in my other cell phone. Maybe Alpha it's not compatible with this version, i saw other issue with same problem with Alpha. 
Love this app :)

**Comment by pokesniperandroid** [comment]
Hi,

If anyone can give us logcat, it'll helpful for fixing this issue on Samsung devices.

**Comment by samchoi02** [comment]
Please fix this bug as soon as possible... Thank you.

**Comment by mokenneth** [comment]
sorry that my device is non-rooted.  cannot provide u the logcat info

**Comment by samchoi02** [comment]
I would love to give my location if it helps you out with updating this app, but I do not know how to find my logcat. (I have a Note 3 lollipop non rooted device) I will be pleased to give my logcat if you tell me the instructions for it. :)

**Comment by samchoi02** [comment]
Sorry for the misspelled word it was because of auto correct. Location -> Logcat

**Comment by samchoi02** [comment]
Hello? This is still a problem here...

**Comment by SamuelPGM** [comment]
Calm down.... lot of problems that they need to face with, One at the time, I think the main one is from the REMOTE SERVER ERROR....

**Comment by ndom1899** [comment]
Force cloce for Lenovo k5 5.0 Android version. Pokesniper 1.5.5

**Comment by ndom1899** [comment]
Experiental 2 Force cloce again. Test with Lenovo k5+

**Comment by ndom1899** [comment]
Experiental 2 Force cloce again. Test with Lenovo k5+. Force cloce with accounting 30 up

**Comment by pokesniperandroid** [comment]
#124

**Comment by ndom1899** [comment]
Force close again with Android 5.0. Lenovo k5
Pada tanggal 18 Feb 2017 3.00 AM, "pokesniperandroid" <
notifications@github.com> menulis:

**Comment by ndom1899** [comment]
Always waiting and so long.
Pada tanggal 18 Feb 2017 03.05, "Lano Rossoneri" <lano.rossoneri@gmail.com>
menulis:

Force close again with Android 5.0. Lenovo k5
Pada tanggal 18 Feb 2017 3.00 AM, "pokesniperandroid" <
notifications@github.com> menulis:

**Comment by ndom1899** [comment]
Still waiting for snipe. Can't snipe. I'm wait for 1 hour.
