### ISSUE TITLE
Google Account

### ISSUE THREAD

**Issue by KHARUROSU** [pokesniperandroid/PokeSniper-Android#97]
Witn version 1.4.0 the app force close in google accout, only works with PTC accounts.
Is it normal?

**Comment by MrCrunchy** [comment]
I'm using Google account without issues. Does it give you an error or just force close? Did you uninstall previous versions?

**Comment by KHARUROSU** [comment]
Forget my problem with v1.4.0. I already uninstalled it to update to the new version. You can close this issue.
Thank you very much.
Keep up the good work.
