### ISSUE TITLE
Razberry

### ISSUE THREAD

**Issue by MrCrunchy** [pokesniperandroid/PokeSniper-Android#98]
Doesn't seem to be using razberry. This just me?

**Comment by pokesniperandroid** [comment]
Try to update to latest version v1.5.1 as the razz berry had been fixed. Need feedback if still facing this issue.

**Comment by MrCrunchy** [comment]
1.5.1 fixed it.  Thanks 😀

**Comment by pokesniperandroid** [comment]
I'll close this then.
